### ISSUE TITLE
Setting clipData to FlClipData.all() in LineChartData hides border.

### ISSUE THREAD

**Issue by LFWarsen** [imaNNeo/fl_chart#1026]
When setting the `clipData` value in `LineChartData` to `FlClipData.all()` the border border of the chart becomes invisible.

I have not tested this with other types of charts or with other `clipData` options.

Without `clipData` value:
![image](https://user-images.githubusercontent.com/29072949/169809221-6c059260-c3b6-434d-ab30-46549e913b2d.png)

With `clipData` set to `FlClipData.all()`:
![image](https://user-images.githubusercontent.com/29072949/169809471-d7cc4515-e80b-436d-bb72-32c89a835772.png)

**Comment by LFWarsen** [comment]
I'm personally no longer working on the project, but maybe @gerardsimons wouldn't mind.

**Comment by imaNNeo** [comment]
Let's follow this in #983
