### ISSUE TITLE
SideTitles can overlap

### ISSUE THREAD

**Issue by RobinJespersen** [imaNNeo/fl_chart#1032]
**Describe the bug**
SideTitles can overlap.

**To Reproduce**
https://github.com/RobinJespersen/flutter_application_fl_chart
```
flutter create .
flutter run
```

**Screenshots**
![Bildschirmfoto 2022-05-25 um 12 26 57](https://user-images.githubusercontent.com/5261252/170241725-27b35647-c9a2-436f-a7f7-c0f8fb0363a2.png)

**Versions**
 - Flutter 3.0.1
 - FlChart 0.50.6

**Problem**
Using a custom interval does not really solve the problem as it needs to adapt to the chart size.
Thus, I think this problem should be solved within the library.

If found this method that seems to be used to compute the interval.
https://github.com/imaNNeoFighT/fl_chart/blob/fdd46e4ed987fd61c7732a3e9664d57d759bbff3/lib/src/utils/utils.dart#L129-L141

It is referenced here:
https://github.com/imaNNeoFighT/fl_chart/blob/25e3815826c8a0f54373015599ececee3cac13ff/lib/src/chart/base/axis_chart/side_titles/side_titles_widget.dart#L113-L116
and here:
https://github.com/imaNNeoFighT/fl_chart/blob/c75f43208f34fb797d8505300b6e4f34c4136ec1/lib/src/chart/base/axis_chart/axis_chart_painter.dart#L52-L55
but the `pixelPerInterval` parameter is never used.

**Suggestion**
Add one parameter `widgetWidth` to the SideTitles class and pass this down to those function calls.

**Comment by CharlotteBenard** [comment]
Any news on this issue? It really is annoying to be forced to rotate titles to make them fit in the graph...

**Comment by imaNNeo** [comment]
Yes, when the title is longer you can rotate them to fix the overlap issue.
BTW there is a duplicate issue here: #906. Please follow it.
