### ISSUE TITLE
where is the SideTitleWidget? I can't find it while trying to use BarChartSample7

### ISSUE THREAD

**Issue by adnanatif** [imaNNeo/fl_chart#1034]
** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.

**Describe the bug**

**To Reproduce**
Provide us a completely reproducible code (contains the main function) in a `main.dart` file, it helps us to find the bug immediately.

**Screenshots**
If applicable, add screenshots, or videoshots to help explain your problem.

**Versions**
 - which version of the Flutter are you using?
 - which version of the FlChart are you using?

**Comment by adnanatif** [comment]
`AxisTitles(
                      sideTitles: SideTitles(
                        showTitles: true,
                        reservedSize: 36,
                        getTitlesWidget: (value, meta) {
                          final index = value.toInt();
                          return SideTitleWidget(
                            axisSide: meta.axisSide,
                            child: _IconWidget(
                              color: BarChartSample7.dataList[index].color,
                              isSelected: touchedGroupIndex == index,
                            ),
                          );
                        },
                      ),
                    ),`

**Comment by adnanatif** [comment]
red line on SideTitleWidget how should i fix it..

**Comment by roly151** [comment]
Try just returning the IconWidget (not a SideTitleWidget). I had a similar issue and just returned a TextWidget which worked fine.

**Comment by imaNNeoFighT** [comment]
How did you get this error?
Are you copying the code to your project?
