### ISSUE TITLE
[Question] LineChartData multiple line bars, is it possible to render tooltips for only one line bar?

### ISSUE THREAD

**Issue by defuncart** [imaNNeo/fl_chart#1092]
Firstly, thank you for creating this fantastic package. I looked through the open and closed issues and did not spot anything related.

For `LineChartData`, when `lineBarsData` contains multiple line bars (as seen in the example), is it possible to render the tooltip for only one line bar?
![Bildschirmfoto 2022-07-11 um 12 20 17](https://user-images.githubusercontent.com/13286425/178243507-f67c446a-f77c-4763-84a0-ee5b678e036c.png)
 
So considering the example above, I'd like to render a tooltip for the blue line without rendering any tooltip for the purple or green line, and for everything right of the blue line, I'd like to render a tooltip for the green line.

### What I've tried

`LineChartData` can be given a `LineTouchData`, `LineTouchData` has `LineTouchTooltipData` and `getTooltipItems` can be used to return `List<LineTooltipItem`. If a single item is returned, then [an exception](https://github.com/imaNNeoFighT/fl_chart/blob/master/lib/src/chart/line_chart/line_chart_painter.dart#L1013) is raised:

```
tooltipItems and touchedSpots size should be same
```
by `drawTouchTooltip` from `LineChartPainter`. If `showingTooltipSpots.showingSpots` is over-ridden to have the same length as `tooltipItems`, then everything in the chart seems to be rendered correctly

```dart
if (tooltipItems.length != showingTooltipSpots.showingSpots.length) {
      showingTooltipSpots = ShowingTooltipIndicators(
          showingTooltipSpots.showingSpots.take(tooltipItems.length).toList());
}
```

![Bildschirmfoto 2022-07-11 um 12 51 28](https://user-images.githubusercontent.com/13286425/178248728-1818c507-035d-4556-888b-5716bda81af1.png)

Is this exception really required? Is the workaround mentioned viable? Or maybe there is something I have missed?

**Comment by imaNNeoFighT** [comment]
I don't remember why we wrote that line to throw exception. But I tried to implement what you want, you can pass null in positions that you don't want to show anything.
For example, in the below code, we only return a non-null value at index 0:
```dart
getTooltipItems: (List<LineBarSpot> spots) {
  return spots.asMap().entries.map((e) {
    int index = e.key;
    if (index != 0) {
      return null;
    }
    LineBarSpot spot = e.value;
    return LineTooltipItem(spot.y.toString(), const TextStyle());
  }).toList();
}
```

**Comment by theBraun** [comment]
Your solution only works if you want less than the amount of lines - but I tried to create a toolti with more tooltip items in order to add a title for date, and for splitting the info to categories, and got the same exception obviously - Is it an abuse? I wish there was an option to simply return a Widget with whatever content I want for the tooltip...

**Comment by FMorschel** [comment]
Hi everyone! I was struggling with this as well, I even created #1453 (missed this issue). My comment there is how I managed to work around this. 

I admit that this is a bit more complex for the processor to always have to test, but at lest in my case, this worked just fine

**Comment by imaNNeo** [comment]
I've updated the [LineChartSample 6](https://github.com/imaNNeo/fl_chart/blob/main/example/lib/presentation/samples/line/line_chart_sample6.dart) to implement your use-case. For more information, take a look at my answer [here](https://github.com/imaNNeo/fl_chart/issues/1620#issuecomment-2101709690).
https://github.com/imaNNeo/fl_chart/assets/7009300/c9eded61-712f-430a-8880-c422ba7efb15

**Comment by KiddoV** [comment]
Hi, [imaNNeo](https://github.com/imaNNeo)!
I followed your suggestion, but the tooltip left a space at the bottom... not sure why...

<img width="315" height="465" alt="Image" src="https://github.com/user-attachments/assets/b2705253-b24b-4f51-a3ee-51f7a674e8d8" />

My code:
```dart
lineTouchData: LineTouchData(
                    touchTooltipData: LineTouchTooltipData(
                      getTooltipColor: (g) => Theme.of(ctx).scaffoldBackgroundColor.withAlpha(250),
                      tooltipPadding: const EdgeInsets.fromLTRB(10, 5, 10, 0),
                      maxContentWidth: .infinity,
                      getTooltipItems: (lbSpots) {
return lbSpots.asMap().entries.map((e) {
                          if (e.key != 0) return null;
                          // Only display 1 index since we use custom display style
                          return LineTooltipItem(
                            "${date.month}/${date.day}/${date.year}\n",
                            TextStyle(fontSize: 12, color: Theme.of(ctx).colorScheme.onSurface),
}).toList()
}
```
