### ISSUE TITLE
Getting large gap in between data

### ISSUE THREAD

**Issue by Ec04222002** [imaNNeo/fl_chart#1098]
I am not sure why, but there seems to be a large gap between my graphs. I am using rapid API and YH finance API [https://rapidapi.com/apidojo/api/yh-finance] to graph the TSLA stocks data within the 5D range. There is supposedly around 250 data points.  Is there a parameter for this? Could there possibly be a rounding issue? How do I fix this? Thanks in advance.

![Screenshot 2022-07-18 150407](https://user-images.githubusercontent.com/63486469/179609278-6c531042-cbe4-4d33-a8e3-9f6860270f57.png)

**Comment by imaNNeoFighT** [comment]
I didn't understand the problem. Can you please give more details and reproducible code?
