### ISSUE TITLE
[Question] - Horizontal BarChart

### ISSUE THREAD

**Issue by brenoasm** [imaNNeo/fl_chart#1099]
Is there a way to render barCharts horizontally? I tried to search in the docs and do something in the code, but I wasn't very successful. If yes, would be a nice improve to put it into the docs. Thanks.

**Comment by ZingerLittleBee** [comment]
Hi,
Do you got it, I'am confused too.
I'am tried to use `Transform.rotate`, but seem not good.

**Comment by leandrorazevedo** [comment]
I have the same issue. I've searched through all the documentation and haven't found anything.

**Comment by Mae623** [comment]
The same with me

**Comment by Mae623** [comment]
let's have a look on #113

**Comment by imaNNeo** [comment]
Yes it is duplicate of #113.
