### ISSUE TITLE
Convert screen offset to chart coordinates

### ISSUE THREAD

**Issue by KapitanPL** [imaNNeo/fl_chart#1147]
### Discussed in https://github.com/imaNNeoFighT/fl_chart/discussions/1135

<div type='discussions-op-text'>

<sup>Originally posted by **KapitanPL** September  3, 2022</sup>
This should be simple, yet I struggle with it. 

How do I convert an offset in pixels to chart coordinates? (or the other way...)</div>

**Comment by imaNNeo** [comment]
Unfortunately, we do not support it at the moment.
We need to implement a way to do that.

**Comment by imaNNeo** [comment]
Duplicate of #801
