### ISSUE TITLE
Calculate maxY based on horizontalInterval

### ISSUE THREAD

**Issue by sgshivamgarg8** [imaNNeo/fl_chart#1186]
In Bar Chart, Currently for data like 100, 200 ,250, 350, 520.
If we dont provide maxY and horizontalInterval
The library calculates horizontalInterval = 100
and maxY = 520 (max value from data)

So the chart shows titles as 0, 100, 200 ,300 ,400, 500, 520

this 520 looks awkward in UI and most of the times overlaps with 500.

Can this maxY be calculated based on auto calculated interval
here in this case it should be 600.

**Comment by imaNNeoFighT** [comment]
Hi. Can you please provide a reproducible code?
