### ISSUE TITLE
RangeAnnotation colors gradient

### ISSUE THREAD

**Issue by tuceturan** [imaNNeo/fl_chart#1195]
Hello I use RangeAnnotations I want annotation background colors gradient But I couldnT Is there any way? or do you add feature?

**Comment by imaNNeoFighT** [comment]
I didn't understand what you want. Please add more details.

**Comment by Parfyonator** [comment]
Hi. I guess @tuceturan wants to be able to add gradient to RangeAnnotation area (see the example).
<img width="701" alt="image" src="https://user-images.githubusercontent.com/27166027/221319779-c184fb60-2731-4cfe-b730-470e51896fa2.png">

**Comment by tuceturan** [comment]
Yes @Parfyonator I couldn't see anywhere

**Comment by imaNNeo** [comment]
Okay, so we need to implement a gradient feature (instead of solid color) for the Range Annotations that we already have. Correct?

**Comment by tuceturan** [comment]
> Okay, so we need to implement a gradient feature (instead of solid color) for the Range Annotations that we already have. Correct?

yes ,Please

**Comment by imaNNeo** [comment]
Added in [0.62.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.62.0).
Please check it out!
