### ISSUE TITLE
Let FlLine accept a gradient or a color

### ISSUE THREAD

**Issue by tanzilzubair** [imaNNeo/fl_chart#1197]
Title pretty much says it all, basically making it so that `FlLine()` can accept both individual colors, or a gradient to color its lines.

**Comment by Dartek12** [comment]
@tanzilzubair, @imaNNeo Please have a look at the PR which aims to solve it: https://github.com/imaNNeo/fl_chart/pull/1446

**Comment by imaNNeo** [comment]
Landed in [0.65.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.65.0)
Check it out!
