### ISSUE TITLE
top of each bar

### ISSUE THREAD

**Issue by fabioselau077** [imaNNeo/fl_chart#1212]
Hello, how do I put a label on top of each bar?
For example, I have 5 bars that contain the value of the top 5 best selling products, so I would like to put each product's name at the top of its Bar

**Comment by imaNNeo** [comment]
Check bar chart sample 3
##### Sample 3 ([Source Code](https://github.com/imaNNeo/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample3.dart))
<img src="https://github.com/imaNNeo/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_3.png" width="300" >

**Comment by fabioselau077** [comment]
> Check bar chart sample 3
> 
> ##### Sample 3 ([Source Code](https://github.com/imaNNeo/fl_chart/blob/master/example/lib/bar_chart/samples/bar_chart_sample3.dart))
> <img alt="" width="300" src="https://github.com/imaNNeo/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_3.png">

Hello, thanks for reply.
In the case is top label in each bar
![image](https://user-images.githubusercontent.com/57275833/214416543-c5ffc675-3341-48b1-9032-5e299fc7dfdf.png)

**Comment by imaNNeo** [comment]
So you want to show a number on top of a single bar?

**Comment by fabioselau077** [comment]
> So you want to show a number on top of a single bar?

Yup, but in reality I want to do something like this. At the bottom of each bar show the seller's name and at the top of each bar show the value:
![image](https://user-images.githubusercontent.com/57275833/214426915-65f66830-a72a-4d61-8ff4-0b32e61795ca.png)

Or at the top show the name of the seller and inside the bar show its value.
Either one of the two already meets my needs. Can the package do this today? In my research it falls to issues of years ago where you reported that you could ...
![image](https://user-images.githubusercontent.com/57275833/214427271-bb878568-ca97-4d4d-9e6d-cdca9c910297.png)
