### ISSUE TITLE
Add the animation feature of the fl_chart when loading the widget

### ISSUE THREAD

**Issue by kingwebdev0105** [imaNNeo/fl_chart#1253]
Greetings,
I am a **newbie** who has started learning **Flutter**.
Recently, I implemented some **chart** functions using **fl_chart**, but it was too static, so I tried to add an animation feature.

I implemented the desired animation using the parameters `swapAnimationDuration` and `swapAnimationCurve`, but I came here because I wanted to add an **animation effect** like this when the chart is **loaded** on the **widget**.

Your kind response to this matter will be awaited.

Kind regards!

**Comment by imaNNeo** [comment]
Hi
There is a duplicate issue about it here: #406
