### ISSUE TITLE
Is it possible to make line chart x axis not consecutive?

### ISSUE THREAD

**Issue by ZonW** [imaNNeo/fl_chart#1264]
![Screenshot 2023-02-15 at 9 04 32 PM](https://user-images.githubusercontent.com/95121369/219249172-71bc74cf-5b92-40bc-8d57-e43820ecac87.png)
Here's my current line chart, x axis are timestamps and y axis is corresponding price data. The problem is that my x axis value is not consecutive and missing some dates like weekends, holidays, etc. But it seems like the chart filled in the missing x axis values automatically and created those weird straight line segments. Is it possible to make it not doing so? So I can still have a contiguous line chart but not having those line segments showing.
For example, I have following spots and I want 7 go directly after 4 on the x axis. 
```
spots: [
            FlSpot(0, 0),
            FlSpot(1, 1),
            FlSpot(2, 2),
            FlSpot(3, 3),
            FlSpot(4, 4),
           
            FlSpot(7, 7),
            FlSpot(8, 8),
            FlSpot(9, 9),
            FlSpot(10, 10),
       ],
```

**Comment by imaNNeo** [comment]
Is it related to something like this issue: #438 ?

**Comment by ZonW** [comment]
> 
Thanks for the reply.
Yeah, I was using the same method as stated by @Monolite in #438 by plotting the graph using milliseconds timestamps to double. But in my case, the x axis does not have a consecutive milliseconds interval. The application is similar to #444 but using weekly, monthly, yearly data thus missing some data for specific dates.
Here's a piece of code I'm using.
```
var response = await http.get(Uri.parse(
        'http://10.0.2.2:8000/history?symbol=$ticker&interval=$interval&period=$period'));
    if (response.statusCode == 200) {
      var data = json.decode(response.body);
      //format the history data to FLchart format
      List<FlSpot> stockData = [];
      for (var time in data['Close'].keys) {
        stockData.add(
          FlSpot(double.parse(time), data['Close'][time]),
        );
      }
```

**Comment by ZonW** [comment]
Solved by setting FLSpot x values as consecutive indexes instead of timestamps. And use separate Map<int, double>global variable to map each timestamp to the index. The map is then used for axis labeling or touchtooltip display.
```
      List<FlSpot> stockData = [];
      for (int i = 0; i < data['Close'].keys.length; i++) {
        _xAxisLabel[i] = double.parse(data['Close'].keys.elementAt(i));
        double price = data['Close'][data['Close'].keys.elementAt(i)];
        stockData.add(
          FlSpot(i.toDouble(), price),
        );
```

**Comment by cyapa** [comment]
@ZonW so ultimately you had to make your X axis values consecutive in order to render the graph?

 And spots with X values missing from FISpot(5,5), FlSpot(6,6) are shown as a straight line still 🤔 


`
spots: [
            FlSpot(0, 0),
            FlSpot(1, 1),
            FlSpot(2, 2),
            FlSpot(3, 3),
            FlSpot(4, 4),
           
            FlSpot(7, 7),
            FlSpot(8, 8),
            FlSpot(9, 9),
            FlSpot(10, 10),
       ],
`
