### ISSUE TITLE
Bar Chart Example 6 import problem

### ISSUE THREAD

**Issue by mrks89** [imaNNeo/fl_chart#1265]
In the source code of Bar Chart Example 3 the following imports are made: 

`import 'package:fl_chart_app/presentation/resources/app_resources.dart';
import 'package:fl_chart_app/util/extensions/color_extensions.dart';`

but these are not within the fl_chart package. How can one include them? Might be a good idea to add this info to the example as well.

**Comment by imaNNeo** [comment]
Can you please run `flutter clean; flutter pub get` and then `flutter run` in the `example/` directory?

**Comment by mrks89** [comment]
I have not cloned the repo but try using it in my project. Linechart examples work by importing the fl_chart library only. But this bar chart example has the mentioned two dependencies which are not in the fl_chart library when installing. --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 18.02.23, 18:29 schrieb imaNNeo ***@***.***>:

   
  Can you please run flutter clean; flutter pub get and then flutter run in the example/ directory?

**Comment by imaNNeo** [comment]
Aha. So the examples are not standalone files. 
You should clone the project to run the example files.
