### ISSUE TITLE
Set border radius to section data

### ISSUE THREAD

**Issue by SebastianKlaiber** [imaNNeo/fl_chart#1268]
Is there a possibility to set a border radius at the section data? The start and end of the sections are rounded. So far, I couldn't find a way to do this.

![image](https://user-images.githubusercontent.com/59142/220046307-1ff69db6-def9-4c23-af80-df64c5cf2e69.png)

**Comment by imaNNeo** [comment]
Duplicate of #1175

**Comment by zjoart** [comment]
were you able to find a solution @SebastianKlaiber
