### ISSUE TITLE
My Chart needs touch show more Data

### ISSUE THREAD

**Issue by helloworkcupid** [imaNNeo/fl_chart#1269]
** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.
fl_chart : 0.55
flutter :
[✓] Flutter (Channel beta, 3.3.0-0.5.pre, on macOS 13.2 22D49 darwin-arm, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.75.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
**Is your feature request relasted to a problem? Please describe.**

I want to display some data other than coordinate value when the chart is displayed by touch, such as the name of the curve. How to achieve this?  includd,linechart,barchart.
thank you

**Describe the solution you'd like**

<img width="294" alt="企业微信截图_92ffa423-3e9d-4d5d-a8d2-149a67dbaf99" src="https://user-images.githubusercontent.com/25734405/220263074-c4eeb860-78d7-41d1-95ec-ce73ace8a6be.png">

<img width="286" alt="企业微信截图_0fd9f263-59b6-4a4e-81b4-61ab8d6597f7" src="https://user-images.githubusercontent.com/25734405/220263220-f2593a35-0b88-4631-a70b-fbc46d658b0c.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by imaNNeo** [comment]
Please check the BarChartSample1:
(You can do the same in LineChart)

##### Sample 1 ([Source Code](https://github.com/imaNNeo/fl_chart/blob/master/example/lib/presentation/samples/bar/bar_chart_sample1.dart))
<img src="https://github.com/imaNNeo/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_1.gif" width="300" >

**Comment by helloworkcupid** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/25734405/222018872-511557f8-8976-4a28-ad30-7a508ebe9661.png">

I want to display text information in the way of not wrapping, or in a certain width of internal wrapping, how to configure? thank you，as the question on the linechart

**Comment by imaNNeo** [comment]
You need to increase the tooltip `maxContentWidth` property in the [LineTouchTooltipData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetouchtooltipdata) or [BarTouchTooltipData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/bar_chart.md#BarTouchTooltipData).
