### ISSUE TITLE
How to round corners LineChart 

### ISSUE THREAD

**Issue by NamBuiDanh2001** [imaNNeo/fl_chart#1278]
** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.

**Is your feature request relasted to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I wonder if it is possible to round the corner of LineChart , like image below
<img width="191" alt="Screen Shot 2023-03-03 at 13 43 59" src="https://user-images.githubusercontent.com/29246888/222667167-c27a4a2f-fa1e-4b7e-bf1c-0fed2876409d.png">

**Comment by imaNNeo** [comment]
You can use [ClipRRect](https://api.flutter.dev/flutter/widgets/ClipRRect-class.html) class.
