### ISSUE TITLE
Dynamically changing tooltipBgColor

### ISSUE THREAD

**Issue by davide-capozzi** [imaNNeo/fl_chart#1279]
**Don't make a duplicate issue.**
I didn't find anything like this, sorry if i missed something

**Is your feature request relasted to a problem? Please describe.**
I would like to be able to dynamically change the `tooltipBgColor`, in the same way `getTooltipItems` allows to change the **_text_** of a tooltip

**Describe the solution you'd like**
 Ideally this change would be included in the `tooltipItem` so that also the popup can be configured in the same place, the expected behaviour at the end is the ability to show tooltips of different colors based on the y value of the line, (i.e: i would like to have tooltips for points below 0 to have a black background and tooltips above 0 to have a white background)

**Describe alternatives you've considered**
i have considered just changing the color of the text, but changing the color of the background is really what i would like to achieve

**Additional context**
This is the tooltip i'm talking about, i hope it's clear enought even if i don't provide example with both colors 
![Screenshot 2023-03-06 at 14 36 12](https://user-images.githubusercontent.com/125470225/223125338-19ba5409-750b-4c00-910f-dcc0aaf7334b.png)

If there is already a way to do this could you show me an example?

**Comment by imaNNeo** [comment]
So we need to implement a callback to receive a color based on the provided data to paint the background.
We should do this for all of line, bar and scatter charts to keep the consistency.

**Comment by apekshamehta** [comment]
Hi, I have been working as an iOS application developer for about 4.5 years, and I am currently learning Flutter. I would like to contribute to your open-source project, starting with the change mentioned above. I am in the process of setting up the code base.

**Comment by imaNNeo** [comment]
@apekshamehta Correct choice :)) 
I was an Android developer for about 7 years, now I completely switched to Flutter and to be honest, it's beautiful.
btw, welcome to the Flutter world

You can start working on this issue, read the code, you can find some samples that we have a callback to get the color from the user.

Don't forget to read the [contributing guideline](https://github.com/imaNNeo/fl_chart/blob/master/CONTRIBUTING.md)

**Comment by apekshamehta** [comment]
@imaNNeo 
Thank you for your response, and I apologize for the delayed reply. I was on vacation.

I wanted to provide an update regarding the changes I made. The implementation can be reviewed in my branch named "feature/dynamic-tooltip-bgcolor." Additionally, I have provided comprehensive details regarding the changes in my pull request. I kindly request your valuable feedback on the modifications I have made.

**Comment by imaNNeo** [comment]
> t. I kindly request your valuable feedback on the modifications I have made.

Good to have your PR ready, I've written some comments. check them out

**Comment by sivaperumal202009** [comment]
This feature looks good. @imaNNeo can we expect this anytime soon?

**Comment by iamiota** [comment]
There are 2 lines with different colors on a chart, and they have `tooltips` with their respective `tooltipBgColor`. 
This makes sense.

**Comment by imaNNeo** [comment]
Added `getTooltipColor` getter in [0.67.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.67.0)
Don't forget to read the [migration guide](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/migration_guides/0.67.0/MIGRATION_00_67_00.md) carefully
