### ISSUE TITLE
Curved Line graph goes beyond zero in zero postion in y axis

### ISSUE THREAD

**Issue by imdewan** [imaNNeo/fl_chart#1281]
![simulator_screenshot_17B13B52-5DC9-45A8-B896-FCE5EEDF59B1](https://user-images.githubusercontent.com/65299428/223762438-8c4965b3-f94c-4c33-8883-d5dc077face2.png)

you can see the curve going beyond the min value, is there anyway to limit this?

**Comment by imaNNeo** [comment]
Duplicate, 
check this issue: #25

**Comment by imdewan** [comment]
Thanks
