### ISSUE TITLE
I can't draw a horizontal line

### ISSUE THREAD

**Issue by jupeng123** [imaNNeo/fl_chart#1284]
**Describe the bug**
y is equal to the maximum and I can't draw a horizontal line

**To Reproduce**
extraLinesData: ExtraLinesData( horizontalLines: [
        HorizontalLine(
          y: maxY,
          color: Colors.red,
          strokeWidth: 0.5,
          dashArray: [1, 1],
        )
      ]),

**Screenshots**
If applicable, add screenshots, or videoshots to help explain your problem.

**Versions**
 [0.61.0]

**Comment by imaNNeo** [comment]
Dup of #1255
