### ISSUE TITLE
How to control spacing between bottomTitles? 

### ISSUE THREAD

**Issue by SamedHrmn** [imaNNeo/fl_chart#1285]
I want to give spacing between bottomSide titles but I can't find any property for this.
 
 I tried to wrap SideTitleWidget with Container and giving margin but did not effect. Is there a way for this ? 

![image](https://user-images.githubusercontent.com/60006881/225655119-249b78e5-3242-4745-8b96-68cb87ac9e5e.png)

**Comment by imaNNeo** [comment]
You are using an axis-based chart, so titles draw based on the axis value,
for example, in the x-coordinate, you have 0 to 6 values. So chart devices the space to put the 0 to 6 values in the x-coordinate.
btw you can tweak the maxX value.

**Comment by GraSim** [comment]
Hi, I don't want to open the exact same issue but currently (as at 23 Jun 2024), there is no **maxX** property. Is there a current solution for  overlapping titles?
