### ISSUE TITLE
bottomTitleWidget or leftTitleWidget often  content is out of bounds or overlapping

### ISSUE THREAD

**Issue by AlmostSir777** [imaNNeo/fl_chart#1292]
The data dynamic span is large, and the minimum and maximum values cannot be controlled. I don't know how to handle this problem
![Simulator Screen Shot - iPhone 11 - 2023-03-23 at 22 51 47](https://user-images.githubusercontent.com/16682438/227242788-3084b4db-d356-4001-9b0d-777e589171d9.png)
![Simulator Screen Shot - iPhone 11 - 2023-03-23 at 22 53 48](https://user-images.githubusercontent.com/16682438/227242869-77af5284-26ee-4a41-9b97-2b9c84495224.png)

**Comment by imaNNeo** [comment]
Dup of #906
