### ISSUE TITLE
Customizable TouchToolTipBuilder

### ISSUE THREAD

**Issue by Omasyo** [imaNNeo/fl_chart#1295]
Currently we can only get a tooltip for the graphs by implementing the respective TouchToolTipData. But this approach doesn't allow the user to modify, add or change the layout/contents of the tooltip. Additionally it doesn't allow for the implementation of custom shapes/designs and decorations(like adding shadows or gradients).

My suggestion is for the addition of a TocuhToolTipBuilder that allows the user to create custom tooltip objects/widgets which can be used in place of the ToolTipData. This can allow users to design/customize their tooltip as they see fit.

**Comment by imaNNeo** [comment]
Dup of #72
