### ISSUE TITLE
Automatically match the Y-axis (Y-axis)

### ISSUE THREAD

**Issue by helloworkcupid** [imaNNeo/fl_chart#1296]
** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.
fl_chart: ^0.55.1
**Is your feature request relasted to a problem? Please describe.**

Automatically match the Y-axis (Y-axis). If it is shown, my data range varies greatly from 0 to 10 billion, so how should I set it to make the display of the Y-axis more beautiful?

my data set :

Widget leftTitleWidgets(double value, TitleMeta meta) {
    const style = TextStyle(
      color: Color(0xff75729e),
      fontWeight: FontWeight.bold,
      fontSize: 10,
    );
    String text;
    // if (timeType.isNotEmpty && timeType.contains('租金收入')) {
    if (isMax100) {
      switch (value.toInt()) {
        case 0:
          text = '0';
          break;
        case 10:
          text = '10';
          break;
        case 20:
          text = '20';
          break;
        case 30:
          text = '30';
          break;
        case 40:
          text = '40';
          break;
        case 50:
          text = '50';
          break;
        case 60:
          text = '60';
          break;
        case 70:
          text = '70';
          break;
        case 80:
          text = '80';
          break;
        case 90:
          text = '90';
          break;
        case 100:
          text = '100';
          break;

        default:
          return Container();
      }
    }

Please tell me how to set the ordinate more succinctly to make my code more concise. For example, when the data range is within 100, 0,10,20,30 ，，，，, when the data range is 0-60000, 0,10000,20000, etc., the ordinate can be displayed beautifully. thank you

![Screenshot_20230403_152827_com zhui sg sg_invest host](https://user-images.githubusercontent.com/25734405/229475697-0641b482-0c7e-41a5-9e67-0d9aa97ba1ad.jpg)

![Screenshot_20230403_152827_com zhui sg sg_invest host_副本](https://user-images.githubusercontent.com/25734405/229476471-b4dbd75a-3f3c-4e2b-87e8-1c9c4a859041.jpeg)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by helloworkcupid** [comment]
![image](https://user-images.githubusercontent.com/25734405/229700949-3b576206-a0e1-4928-8b33-9bd4c741b305.png)
 Widget leftTitleWidgets(double value, TitleMeta meta) {
    const style = TextStyle(
      color: Color(0xff75729e),
      fontWeight: FontWeight.bold,
      fontSize: 10,
    );
    String text;
    // if (timeType.isNotEmpty && timeType.contains('租金收入')) {
    if (isMax100) {
      switch (value.toInt()) {
        case 0:
          text = '0';
          break;
        case 10:
          text = '10';
          break;
        case 20:
          text = '20';
          break;
        case 30:
          text = '30';
          break;
        case 40:
          text = '40';
          break;
        case 50:
          text = '50';
          break;
        case 60:
          text = '60';
          break;
        case 70:
          text = '70';
          break;
        case 80:
          text = '80';
          break;
        case 90:
          text = '90';
          break;
        case 100:
          text = '100';
          break;

        default:
          return Container();
      }

set my leftTitleWidgets ,as top ;
so How to avoid the above situation and indirectly optimize the code, thank you

**Comment by imaNNeo** [comment]
Hi
I couldn't understand the problem.
Please format your code (or put it in a main.dart file).
Also, decrease your image sizes, because it is like a 10 page scroll to see an image.

**Comment by helloworkcupid** [comment]
I want to realize the adaptive display of Y-axis labeling. According to the actual data, it can be perfectly adaptive labeling from 0 to millions, billions, thank you

**Comment by imaNNeo** [comment]
Is this issue related to #434?

**Comment by helloworkcupid** [comment]
so, can you tell me the code for this ? thanks

**Comment by imaNNeo** [comment]
Do you need the logarithmic axis?

**Comment by imaNNeo** [comment]
It seems [you need the logarithmic axis feature](https://github.com/imaNNeo/fl_chart/issues/434#issuecomment-1506156670).
So we do not have this feature at the moment. 
btw, you can follow the #434 thread to read some workarounds about it.

**Comment by helloworkcupid** [comment]
thank you
