### ISSUE TITLE
the bar Figure out of range

### ISSUE THREAD

**Issue by helloworkcupid** [imaNNeo/fl_chart#1298]
** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.

**Is your feature request relasted to a problem? Please describe.**
fl_chart: ^0.55.1
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/25734405/229707832-30061f54-97d1-4a18-90bd-fccf2c8a274f.png)
How do I set it up so that it doesn't happen like that, thank you
How do I set it up so that it doesn't happen like that, thank you
**Describe alternatives you've considered**

**Additional context**

**Comment by helloworkcupid** [comment]
now anoter question :
![image](https://user-images.githubusercontent.com/25734405/229709725-130775de-df7b-42d7-8fd2-b826d6805bb3.png)
I wanted the touch data to be displayed longer, hiding the previous data only when the finger was off the screen and touching other data

**Comment by imaNNeo** [comment]
Hi
I couldn't understand the problem.
Please provide more information, your description is our issue template without any new data.

**Comment by helloworkcupid** [comment]
I mean, when I touch the screen with my finger to display the data, can I keep the data on display until the next click happens, thank you

**Comment by imaNNeo** [comment]
> I mean, when I touch the screen with my finger to display the data, can I keep the data on display until the next click happens, thank you

Check this one:
https://github.com/imaNNeo/fl_chart/issues/868#issuecomment-1059229083
