### ISSUE TITLE
Side titles alignment for titles on the edges of the axis are broken

### ISSUE THREAD

**Issue by nickboris** [imaNNeo/fl_chart#1301]
![image](https://user-images.githubusercontent.com/125840990/230532249-07cfde91-abcc-4f12-bc7f-e45a883f73ff.png)

Seeing the above happen (on both axis the titles on the outsides of the list of titles and brought closer together) when I apply the following SideTitleFitInsideData: 

`return SideTitleWidget(
                            child: text,
                            axisSide: AxisSide.bottom,
                            fitInside: SideTitleFitInsideData.fromTitleMeta(
                                meta,
                                distanceFromEdge: 8),
                          );`

Why does this happen? It seems like the meta data has some additional padding applied. When I try to not use fromTitleMeta and assign the required parameters it seems to break in other ways. Am unable to tell what the parameters are meant to do based on the documentation so I could be missing something simple.

**Comment by imaNNeo** [comment]
You need to set `fitInside: SideTitleFitInsideData.disable()` to disable the function for fitting titles inside.
To learn more about it, check this PR: #1257

**Comment by nickboris** [comment]
Would disabling it allow me to distance the titles from the axis? That’s the reason I added them in the first place, because the chart line would overlap the text elements on the bottom axis.

**Comment by imaNNeo** [comment]
You can put extra space around the first and last title by wrapping your child with a Padding widget.

**Comment by nickboris** [comment]
I don’t think we’re on the same page here. The padding around the first and last titles is the bug, not what I want. What I wanted was to use the distanceFromEdge field to move the bottom axis titles away from the axis itself. It did so correctly, but had the side effect of applying padding to the left of the first title, and to the right of the last title, pushing them towards the inside. I’m not sure why that happened, because I intended only to apply spacing between the title and the axis they are applied to. Does that make sense?

**Comment by imaNNeo** [comment]
`distanceFromEdge` is not moving the titles line from the axis line. It just a distance between the first and last title from the edges. For example, suppose you add this on the bottom titles, it adds a space to the left of first title and right of last title.

So if you want to move the titles line away from the axis line, you should disable this feature (if you don't want it), then you can wrap your widgets with Padding and put a top space, also you need to increase the reservedSize.
I have created a sample for you:
Check it in the [zapp](https://zapp.run/edit/flutter-zv4606bqv470?entry=lib/main.dart&file=lib/main.dart)

https://user-images.githubusercontent.com/7009300/231203652-c5a0113d-ef16-4433-80a8-1ae7ea58c606.mov
