### ISSUE TITLE
static (constant) horizontal lines in Line Chart

### ISSUE THREAD

**Issue by AndroidDesigner** [imaNNeo/fl_chart#1314]
Hello
I want to show multiple predefined horizontal lines that are not included in my y-axis values.
I did see ``FlGridData`` has ``getDrawingHorizontalLine`` property, but it does not allow me to show my own desired predefined horizontal lines on a line chart.
what is solution?

**Comment by imaNNeo** [comment]
Hi there,

You need to use `extraLinesData` in your LineChartData class.
