### ISSUE TITLE
Line chart with colors for certain ranges

### ISSUE THREAD

**Issue by zkrige** [imaNNeo/fl_chart#1317]
Is it possible to have the line color match certain ranges. Sort of like range annotations, but we dont want the extra annotation on the graph.

eg:
- if 0 >= y-value <= 10, line color is red
- if 10 < y-value <= 20, line color is blue
- if 20 < y-value, line color is green

here is a chart to illustrate (the values dont match the ranges I mentioned above, but it should demonstrate the idea)
![image](https://user-images.githubusercontent.com/968412/232765222-33f9f979-c3a3-45dc-b34d-04a7fba70eac.png)

**Comment by imaNNeo** [comment]
There is a duplicate issue about it: #1044 
Please put your image as a sample in that thread, also don't forget to thum-up the issue
