### ISSUE TITLE
Check to show side titles

### ISSUE THREAD

**Issue by praveengitsit** [imaNNeo/fl_chart#1320]
I am unable to find any kind of bool check for showing side titles, similar to one we have for showing a vertical or horizontal line `checkToShowVerticalLine`.

My use case is a simple one:

1. I am working on a graph whose `minX` value starts from 16.
2. The X-axis titles should have an interval of 6. But not in the fashion of: 0,6,12,18,24. It is more in the fashion of 16,22,28,34.
3. The `SideTitles` class only provides a way to enter an `interval` to it. This renders my side titles as 16,18,24,30, which makes the UI look inconsistent. 
  ![Screenshot 2023-04-25 at 12 59 05](https://user-images.githubusercontent.com/45666428/234201815-4e31f21f-368a-40d7-9ec6-74dd51d03396.png)

If there was some flag for showing side titles, based on the value, this would be really helpful. 
If there is any other viable workaround for this, I'd be happy to implement the alternative.

I have tried a workaround, where the value starts from 12 (a factor of the interval 6). But this gives room for some false assumption about data starting from 12, when in fact it always starts from 16.

**Comment by imaNNeo** [comment]
You can override the `getTitlesWidget` callback in the [SideTitles](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/base_chart.md#sidetitles) class. Then you can return an empty `Container()` or `SizedBox()` where you don't want to show title.

**Comment by imaNNeo** [comment]
You can override the `getTitlesWidget` callback in the [SideTitles](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/base_chart.md#sidetitles) class. Then you can return an empty `Container()` or `SizedBox()` wherever you don't want to show title.
