### ISSUE TITLE
Line chart keep FlLine visible 

### ISSUE THREAD

**Issue by zychns** [imaNNeo/fl_chart#1323]
Hi guys,
Can the FlLine be kept visible on the Line chart all the time after the first interaction? 
Currently, the line disappears after each touch. 
In addition is there a way to show x,y cords after touch through callback?

**Comment by reRacer** [comment]
I think I found what I'm looking for on chart #9. Great job with those charts by the way :)

**Comment by zychns** [comment]
I think I found what I'm looking for on the chart https://github.com/imaNNeo/fl_chart/issues/9. Great job with those charts by the way :)

**Comment by zychns** [comment]
I have noticed that on https://app/flchart.dev/#/line (opened on phone) Ion Line chart Sample 9 I can slide from one side to the other and the line stays visible but then I go and use the source code it keeps disappearing.

**Comment by zychns** [comment]
found a solution by setting up showingIndicators (following line chart #5) and adding the following to touchCallback: 
touchCallback: (touchEvent, response) {
                    if (response == null || response.lineBarSpots == null) {
                      return;
                    }
                    if (touchEvent is FlTapDownEvent ||
                        touchEvent is FlPanUpdateEvent) {
                      final spotIndex = response.lineBarSpots!.first.spotIndex;
                      setState(() {
                        showingTooltipOnSpots.clear();
                        showingTooltipOnSpots.add(spotIndex);
                      });
                    }
                  },
