### ISSUE TITLE
getDotPainter drawing DotPointer

### ISSUE THREAD

**Issue by Sardor6628** [imaNNeo/fl_chart#1324]
Is it possible to draw Polygon instead of FlDotCirclePainter? I was developing an app with some special requirements. 

<img width="892" alt="Screenshot 2023-04-27 at 12 10 36 PM" src="https://user-images.githubusercontent.com/39268406/234750740-ae227411-1fa5-4daa-b06c-7a0a28f85559.png">

<img width="892" alt="Screenshot 2023-04-27 at 12 10 36 PM" src="https://user-images.githubusercontent.com/39268406/234750747-db083f18-8bcf-4395-b71a-535616989978.png">

**Comment by Sardor6628** [comment]
@imaNNeo @shamilovtim @payam-zahedi

**Comment by payam-zahedi** [comment]
At the moment, there is no Polygon painter included in this package. However, it is possible to create a custom Polygon painter to suit your needs.

You can create your own painter by extending from `FlDotPainter`.

For an example, you can take a look at this code:

[link](https://github.com/imaNNeo/fl_chart/blob/af4e6fa977062f70661d8cf2620bf9c610e3573c/lib/src/chart/line_chart/line_chart_data.dart#L837)

**Comment by payam-zahedi** [comment]
At the moment, there is no Polygon painter included in this package. However, it is possible to create a custom Polygon painter to suit your needs.

You can create your own painter by extending from `FlDotPainter`.

For an example, you can take a look at this code:

[link](https://github.com/imaNNeo/fl_chart/blob/af4e6fa977062f70661d8cf2620bf9c610e3573c/lib/src/chart/line_chart/line_chart_data.dart#L837)

**Comment by Sardor6628** [comment]
Thank you @payam-zahedi 

Leaving my code here, just in case someone needs something similar.



class PolygonDotPainter extends FlDotPainter {
  final int sides;
  final Color color;
  final double radius;
  final double strokeWidth;
  final Color strokeColor;

  PolygonDotPainter({
    this.sides = 6,
    this.color = Colors.red,
    this.radius = 4,
    this.strokeWidth = 1,
    this.strokeColor = Colors.black,
  });

  @override
  void draw(Canvas canvas, FlSpot spot, Offset offsetInCanvas) {
    final centerX = offsetInCanvas.dx;
    final centerY = offsetInCanvas.dy;

    final path = Path();
    final angle = (2 * pi) / sides;
    final startAngle = -pi / 2;

    path.moveTo(centerX + radius * cos(startAngle), centerY + radius * sin(startAngle));

    for (int i = 1; i <= sides; i++) {
      final currentAngle = startAngle + (i * angle);
      final x = centerX + radius * cos(currentAngle);
      final y = centerY + radius * sin(currentAngle);
      path.lineTo(x, y);
    }

    path.close();

    final paint = Paint()
      ..color = color
      ..strokeWidth = strokeWidth
      ..style = PaintingStyle.fill;

    final strokePaint = Paint()
      ..color = strokeColor
      ..strokeWidth = strokeWidth
      ..style = PaintingStyle.stroke;

    canvas.drawPath(path, paint);
    canvas.drawPath(path, strokePaint);
  }

  @override
  Size getSize(FlSpot spot) {
    return Size(radius * 2, radius * 2);
  }

  @override
  // TODO: implement props
  List<Object?> get props => throw UnimplementedError();
}

**Comment by payam-zahedi** [comment]
Well Done @Sardor6628 
Also, If you have some spare time, it would be great if you could create a pull request for the PolygonDotPainter.

**Comment by Sardor6628** [comment]
@payam-zahedi Sure, I will try to do that on weekends.

**Comment by imaNNeo** [comment]
Thank you, guys!

Yes, I would appreciate if you add it in the package
