### ISSUE TITLE
Wrong RadarChart graph

### ISSUE THREAD

**Issue by riccardocescon** [imaNNeo/fl_chart#1326]
**Describe the bug**
With the following dataset:
```dart
RadarChart(
                    RadarChartData(
                      dataSets: [
                        RadarDataSet(
                          dataEntries: const [
                            RadarEntry(value: 1657),
                            RadarEntry(value: 1553),
                            RadarEntry(value: 1618),
                            RadarEntry(value: 1622),
                            RadarEntry(value: 1494),
                            RadarEntry(value: 1390),
                            RadarEntry(value: 1558),
                            RadarEntry(value: 1274),
                            RadarEntry(value: 1703),
                            RadarEntry(value: 1586),
                            RadarEntry(value: 1251),
                            RadarEntry(value: 1390),
                            RadarEntry(value: 1790),
                            RadarEntry(value: 1328),
                            RadarEntry(value: 1095),
                            RadarEntry(value: 1441),
                            RadarEntry(value: 1047)
                          ],
                        ),
                      ],
                      tickCount: 5,
                    ),
                  );
```
the chart has weird values.

**To Reproduce**
Create a widget with those values,
See the issue

**Screenshots**
![image](https://user-images.githubusercontent.com/36532502/235345960-5a377f87-2ac8-4596-b010-cab823a54eda.png)

Since the lower value is 1047 i expected to see that point as the origin of the chart.
If i set 0 i can see it on the perfect origin point, so i expected to read 0 on the first tickCount not 1047, because this generates a mismatch with the point on the graph

**Versions**
 - which version of the Flutter are you using? Channel stable, 3.7.11,
 - which version of the FlChart are you using? fl_chart: ^0.61.0

**Comment by imaNNeo** [comment]
Can you check it with the latest version of fl_chart ([0.62.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.62.0) at this time)? 

We did some fixes about this issue.

**Comment by riccardocescon** [comment]
I just updated to 0.62.0 and it seems fixed, it seems to work now! Thank you
