### ISSUE TITLE
Add tooltips to Radar Chart

### ISSUE THREAD

**Issue by nav-28** [imaNNeo/fl_chart#1329]
**Is your feature request related to a problem? Please describe.**
Currently, RadarChart doesn't support tooltips. It would be a great feature if it were possible, like in `LineChart`, to have a tooltip when a data item is touched. 

Example of a tooltip on a RadarChart
![Screenshot 2023-04-30 at 9 07 07 PM](https://user-images.githubusercontent.com/54973703/235396078-55f07db6-8d54-4435-ab21-d6886a6c83db.png)

**Comment by imaNNeo** [comment]
Please don't create duplicate issues, you can find this issue with a simple search: #866 
So you can put your sample image there and thumb up the issue.

Thanks!
