### ISSUE TITLE
Interval is unpredictable

### ISSUE THREAD

**Issue by a1573595** [imaNNeo/fl_chart#1330]
**Describe the bug**
When the Y-axis range is 100 ~ 70, the chart interval can be divided into three, but when the Y-axis range is 115 ~ 61, The chart is spaced into four, But the interval of both is (maxY - minY) / 3.

(100 - 70) / 3 = 10.0
(115 - 61) / 3 =  18.0

**To Reproduce**
```dart=
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Sample(),
    ),
  ));
}

class Sample extends StatelessWidget {
  Sample({Key? key}) : super(key: key);

  final maxY = 115; /// 100
  final minY = 61;  /// 70
  late double interval = (maxY - minY) / 3;

  FlGridData get gridData => FlGridData(
      drawVerticalLine: false,
      horizontalInterval: interval.toDouble());

  FlTitlesData get titlesData => FlTitlesData(
        leftTitles: AxisTitles(
          sideTitles: SideTitles(showTitles: false),
        ),
        topTitles: AxisTitles(
          sideTitles: SideTitles(showTitles: false),
        ),
        rightTitles: AxisTitles(
          sideTitles: SideTitles(
            showTitles: true,
            reservedSize: 36,
            interval: interval.toDouble(),
          ),
        ),
        bottomTitles: AxisTitles(
          sideTitles: SideTitles(showTitles: false),
        ),
      );

  LineChartBarData get data => LineChartBarData(
        spots: [],
        isCurved: true,
        dotData: FlDotData(show: false),
        barWidth: 3,
      );

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SizedBox(
        height: 500,
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: LineChart(
            LineChartData(
              minY: minY.toDouble(),
              maxY: maxY.toDouble(),
              gridData: gridData,
              titlesData: titlesData,
              clipData: FlClipData.all(),
              lineBarsData: [data],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Screenshots**
![Range 100~70](https://user-images.githubusercontent.com/25738593/235825219-6109bd47-275d-48cc-861d-f7aa67637e9f.png)
![Range 115~61](https://user-images.githubusercontent.com/25738593/235825233-03701aa5-0c72-4665-834e-bf0ac8d10148.png)

**Versions**
 - which version of the Flutter are you using? 3.7.12
 - which version of the FlChart are you using? 0.62.0

**Comment by imaNNeo** [comment]
Hi there, what is your expected behavior?

**Comment by a1573595** [comment]
> Hi there, what is your expected behavior?

Since the range of the X-axis is variable,
I hope that the same interval can have the same rendering effect,
Fixed rendering position of title and grid.

**Comment by imaNNeo** [comment]
Sorry for my late answer.
I'm pretty sure that you need to change your `baselineY` property in [LineChartData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartdata) 

```dart
baselineY: yourMinY,
```

**Comment by a1573595** [comment]
> This is what exactly you want? ![image](https://user-images.githubusercontent.com/7009300/244174556-513f5ded-c259-481b-94bc-04e4c50fbf78.png)

Work well, thanks.
