### ISSUE TITLE
Background Color between 2 horizontal lines (ExtraLines) in LineChart

### ISSUE THREAD

**Issue by Priyantha-Kingslake** [imaNNeo/fl_chart#1335]
Currently can add background under Lines drawn using lineChartBarData. Make it possible to add background between 2 Horizontal Lines too. Like Following

![image](https://github.com/imaNNeo/fl_chart/assets/125013689/c86a014a-356c-49e2-ab21-13418f13c0cf)

**Comment by imaNNeo** [comment]
You can do that using `betweenBarsData` property in the [LineChartData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartdata)
Check the below sample code:

##### Sample 7 ([Source Code](https://github.com/imaNNeo/fl_chart/blob/master/example/lib/presentation/samples/line/line_chart_sample7.dart))
<img src="https://github.com/imaNNeo/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_7.png" width="300" >

**Comment by Priyantha-Kingslake** [comment]
Sorry If I was not very clear before. I do know that this can be done between 2 line charts defined via [LineChartBarData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/line_chart.md#LineChartBarData). In fact I used this as a workaround to achieve what I needed. What I wanted to do was define a background color between 2 horizontal straight lines which are defined via [ExtraLinesData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/base_chart.md#ExtraLinesData). 
For example, in the image I provided above, the 'Temperature' line is defined using LineChartBarData. It represents the spots with coordinates (x, y). Then I have also defined a line 'Average' which is a straight line that is defined by only providing the y coordinates. So is the upperLimit and lowerLimit lines which are at 0℃ and 35℃. Then I have a background color between them. 
I found that these straight lines can be created using "ExtraLinesData". But I cannot create a colored region between them

**Comment by imaNNeo** [comment]
Aha, got it.
`rangeAnnotations` in [LineChartData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartdata) is your solution. 

Check the below sample:

##### Sample 8 ([Source Code](https://github.com/imaNNeo/fl_chart/blob/master/example/lib/presentation/samples/line/line_chart_sample8.dart))
<img src="https://github.com/imaNNeo/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_8.png" width="300" >

**Comment by Priyantha-Kingslake** [comment]
Ah, Thanks. Looks like I missed it from the documentation.
