### ISSUE TITLE
Line charts curve downward

### ISSUE THREAD

**Issue by Coinners** [imaNNeo/fl_chart#1337]
**Describe the bug**
Line charts curve downward if data contains many Points with x = 0

**To Reproduce**
Use a line chart with isCurved set to true. In my example the chart contains 28 FlSpots with all of them but 3 having x set to 0

**Screenshot**
![image](https://github.com/imaNNeo/fl_chart/assets/70707774/c09fcccb-6962-4f84-b541-a0d3d716e1b3)

**Comment by imaNNeo** [comment]
`preventCurveOverShooting` in [LineChartBarData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/line_chart.md#linechartbardata) might help.
