### ISSUE TITLE
Negative BarChartRodStackItem are not drawn correctly in Flutter 3.10.5 (stable)

### ISSUE THREAD

**Issue by large** [imaNNeo/fl_chart#1347]
**Describe the bug**
When using stacked bars the negative values are not shown correct on flutter v3.11.xx (master channel).
Same code compiled with Flutter v3.7.12 works as expected.

I have also created an issue within Flutter, but I just wanted you to have a heads up
https://github.com/flutter/flutter/issues/123123#issuecomment-1557823151

**To Reproduce**
See this reproduction code: https://github.com/large/partlyflicker
(Little messy since I used code from a bigger app that had issues)

**Screenshots**
Flutter 3.10.5 stable & Flutter 3.11.xx-pre
![Screenshot_1684783930](https://github.com/imaNNeo/fl_chart/assets/535446/3a79f3ae-d51d-42e3-b606-199fa74960bd)

Flutter 3.7.12
![image](https://github.com/imaNNeo/fl_chart/assets/535446/82282fac-567c-4a5b-a1f5-5b6b30bdc313)

**Versions**
Flutter 3.7.12 (as expected)
Flutter 3.10.5 stable & masterchannel 3.11.xx-pre channel (not as expected)
fl_chart v0.62.0

**Comment by imaNNeo** [comment]
we are not going to support the `master` channel. hopefully it will be fixed in the `stable` channel. Otherwise, we need to fix it.

**Comment by k0psutin** [comment]
BarChartRodStackItem is also broken on Flutter 3.10.5 stable channel.

**To Reproduce**
Clone @large code: https://github.com/large/partlyflicker

Use Flutter 3.10.5 from stable.

Android:
![5FA45E9A-2643-41C6-A38E-3D34357EB4AE_1_201_a](https://github.com/imaNNeo/fl_chart/assets/48412269/8e75f5f7-70dc-44b7-b5a2-f4b248fe86c1)

iOS:
![2361F58F-4F09-4F5C-8D26-84AAF91F30F9](https://github.com/imaNNeo/fl_chart/assets/48412269/b4d77ada-688e-4c95-b35c-834b5d591390)

**Comment by large** [comment]
I am AFK and did not test it on stable channel lately. But this is probably an issue related to Impeller (new render engine).

It could be interesting if some could use the stable channel that fails and try to disable Impeller https://docs.flutter.dev/perf/impeller

**Comment by k0psutin** [comment]
Disabling the impeller didn't do anything. But it seems that the impeller is not activated at all? 

I added:
```
  <meta-data
    android:name="io.flutter.embedding.android.EnableImpeller"
    android:value="true" />
``` 

To `androidmanifest.xml` and run @large example with `flutter run --enable-impeller` and the chart seemed to draw correctly:

![7967B515-B0C2-4500-9213-1EE5A617AA0F](https://github.com/imaNNeo/fl_chart/assets/48412269/7842c3e5-9930-41ad-948f-02d8882a2586)

**Comment by large** [comment]
> Disabling the impeller didn't do anything. But it seems that the impeller is not activated at all? 

I used a mac to develop on and impeller is enabled by default there on iOS. Impeller back then had a lot of issues so almost every gfx-related issue pointed to Impeller 😁
(Impeller ate all the memory 256 GB too, so it was a mess).

So your testing shows that Android with stable 3.10.x impeller disabled = failed and enabled = ok?
How is the framerate though. It is probably slow...

**Comment by k0psutin** [comment]
> I used a mac to develop on and impeller is enabled by default there on iOS. Impeller back then had a lot of issues so almost every gfx-related issue pointed to Impeller 😁 (Impeller ate all the memory 256 GB too, so it was a mess).
> 
> So your testing shows that Android with stable 3.10.x impeller disabled = failed and enabled = ok? How is the framerate though. It is probably slow...

It is quite slow and jerky with the impeller enabled, and it seems that it is very volatile as my other project crashed a lot, when I enabled the impeller (to test it).

**Comment by large** [comment]
I have tested stable 3.10.5 on a Android emulator with same results as @k0psutin.
Impeller off = bug showing
Impeller on = bug gone (performance is really bad)

iOS emulator:
Bug is not showing, emu is eating memory though (another impeller bug)...

Downgraded to Flutter 3.7.12; Android emu (performance good), impeller is not possible to enable here.

I find it hard to find the reason for why this happens, maybe a test could be written for the canvasroutine to test?
https://github.com/imaNNeo/fl_chart/blob/c6eca89ad35d6cd6378a1e983c4bdb27e448c16c/lib/src/chart/bar_chart/bar_chart_painter.dart#L289

**Comment by imaNNeo** [comment]
I found the bug 🎉
