### ISSUE TITLE
Why PieChart trigger 4 to 5 times on every touch on an item?

### ISSUE THREAD

**Issue by caiolabate0** [imaNNeo/fl_chart#1359]
**Describe the bug**
I am using PieChart and I noticed that on every single tap, it trigger the method `pieTouchData` 4 to 5 times.
Why that happens?

```
PieChartData(
    pieTouchData: PieTouchData(
    touchCallback: (FlTouchEvent event, pieTouchResponse) {
       debugPrint('here')
    }

```

**One click = 5 logs on console** 
<img width="213" alt="image" src="https://github.com/imaNNeo/fl_chart/assets/99914093/2862285c-b966-4477-9730-918243ae087b">

It shouldn't happen this way, should it?
Tks!
=)

**Comment by imaNNeo** [comment]
It triggers different FlTouchEvents

```
flutter: here, event: Instance of 'FlPanDownEvent'
flutter: here, event: Instance of 'FlTapDownEvent'
flutter: here, event: Instance of 'FlPanCancelEvent'
flutter: here, event: Instance of 'FlTapUpEvent'
```
