### ISSUE TITLE
Radius for ScatterChart

### ISSUE THREAD

**Issue by TimThieff** [imaNNeo/fl_chart#1366]
### Discussed in https://github.com/imaNNeo/fl_chart/discussions/1364

<div type='discussions-op-text'>

<sup>Originally posted by **TimThieff** June 14, 2023</sup>
I want to do a dots with a radius of 1 meter for exemple (my axes are in meter), but if i put 1 for the radius of the scatterSpot, i will changed with the height and width of the chart. I first though of divising the radius by max(height, width), and it works, the radius is constant, but it's not 1 meter, i need a factor (between 100 and 500 i think) to adjust the size.</div>

**Comment by imaNNeo** [comment]
Why you don't put your comment in #1364 ?

**Comment by imaNNeo** [comment]
I will close this one. Please write your comment there.
