### ISSUE TITLE
rotate angle property not working.

### ISSUE THREAD

**Issue by Rohit175041** [imaNNeo/fl_chart#1368]
Rotate angle property not working.
![WhatsApp Image 2023-06-19 at 00 36 32](https://github.com/imaNNeo/fl_chart/assets/98216033/bf051b9c-3bbe-44ec-ac5d-140573f29431)

**Comment by Rohit175041** [comment]
version  fl_chart: ^0.63.0

**Comment by Rohit175041** [comment]
![fl_ch](https://github.com/imaNNeo/fl_chart/assets/98216033/b9c9491d-366a-4854-b447-c97de3813e15)
This is how the graph is looking.

**Comment by imaNNeo** [comment]
There were some breaking changes in [0.50.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.50.0) (migration guide is [here](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/migration_guides/0.50.0/MIGRATION_00_50_00.md)). Please read the [CHANGELOG](https://github.com/imaNNeo/fl_chart/blob/master/CHANGELOG.md) carefully.
