### ISSUE TITLE
I can't find fl_chart_app

### ISSUE THREAD

**Issue by meansoup** [imaNNeo/fl_chart#1369]
In sample code, it need fl_chart_app.
But I can't find it anywhere.
I wonder how nobody query about that.

**Comment by imaNNeo** [comment]
What do you mean?

**Comment by Colton127** [comment]
fl_chart_app is the example app itself: https://github.com/imaNNeo/fl_chart/tree/master/example

```
name: fl_chart_app
description: FL Chart App is an application to demonstrate samples of the fl_chart (A Flutter package to draw charts).
```
