### ISSUE TITLE
Can I get the vibration to go off when I select and drag a chart?

### ISSUE THREAD

**Issue by ChangDaeJeon** [imaNNeo/fl_chart#1370]
For example, if you have a button, you can use the HapticFeedback.heavyImpact(); function to make the vibration sound when onTap().

LineTouchData(
touchCallback: (p0, p1) => HapticFeedback.heavyImpact())

It can't be implemented in a way, is there a way?
Thank you.

**Comment by imaNNeo** [comment]
You will receive `FlTouchEvent` as the first parameter in the `touchCallback`
You can do whatever you want using happened event.
For example:

```dart
LineTouchData(
   touchCallback: (FlTouchEvent event, pieTouchResponse) {
     if (event is FlTapUpEvent) {
       // Vibrate on tap
     }
   },
);
```
