### ISSUE TITLE
How to change the tooltip line styling in line chart? 

### ISSUE THREAD

**Issue by Pranit1804** [imaNNeo/fl_chart#1373]
I would like to modify both the line width and color of the Tooltip. Is there a way for me to customize these styling options?

Versions
 - flutter version: >=2.18.0 <3.0.10
 - fl_chart version: 0.62.0

**Comment by imaNNeo** [comment]
Yes, please check out our samples: [BarChartSamples](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/bar_chart.md#some-samples), [LineChartSamples](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/line_chart.md#some-samples).
