### ISSUE TITLE
how to make space between a bar graph by using fl_chart package

### ISSUE THREAD

**Issue by newbie0510** [imaNNeo/fl_chart#1374]
![image](https://github.com/imaNNeo/fl_chart/assets/137275804/34f6069e-09e8-4ece-9d1c-f831de2ef01e)

Hello, I wanted to know if it is possible to create a bar chart like the one in the image with this package.
Thanks in advance.

**Comment by imaNNeo** [comment]
Yes, please check out our [BarChartSamples](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/bar_chart.md#some-samples).
