### ISSUE TITLE
Can Tooltips be a custom Widget?

### ISSUE THREAD

**Issue by AkhilrajNambiar** [imaNNeo/fl_chart#1379]
First of all, this library is simply amazing!
But, a small issue which is very amusing is that Tooltips always have to be a custom type. Like LineTooltipItem for LineChart and BarTooltipItem for BarChart. Rather, if we can define a custom widget to be used as a tooltip, it would be much, much more customisable. This is because the custom types (LineTooltipItem, BarTooltipItem, etc.) allow only strings within them.

**Comment by imaNNeo** [comment]
Thank you for your feedback.
Your issue is duplicate, please follow #72
