### ISSUE TITLE
LineChartData LineTouchData enabled  true

### ISSUE THREAD

**Issue by tudosxxx** [imaNNeo/fl_chart#1380]
Is there a way to extend the display time when setting this to true? When I tap and move my finger away or release it, the displayed content disappears immediately. Sometimes, I cannot see the specific numbers because they are blocked by my fingers. I would like to add an additional 2 seconds of display time when the finger is released.

**Comment by tudosxxx** [comment]
`
AspectRatio(
                                aspectRatio: 1.7,
                                child: LineChart(
                                    LineChartData(
                                      lineTouchData: LineTouchData(
                                          enabled: true,
                                          touchTooltipData:LineTouchTooltipData(
                                            tooltipBgColor: Colors.black,
                                            getTooltipItems:(touchedSpots){
                                              return touchedSpots.map((LineBarSpot touchedSpot) {
                                                const textStyle = TextStyle(
                                                  color: Colors.white,
                                                  fontFamily: 'regular3',
                                                  fontSize: 14,
                                                );
                                                return LineTooltipItem(touchedSpot.y.toString(), textStyle);
                                              }).toList();
                                            }
                                          ),
                                      ),
                                      gridData: FlGridData(
                                        show: true,
                                        drawHorizontalLine: true,
                                        drawVerticalLine: true,
                                        verticalInterval: 10,
                                        horizontalInterval: 10,
                                        getDrawingVerticalLine: (value) {
                                          return FlLine(
                                            color: Colors.grey[300],
                                            strokeWidth: 1,
                                          );
                                        },
                                        getDrawingHorizontalLine: (value) {
                                          return FlLine(
                                            color: Colors.grey[300],
                                            strokeWidth: 1,
                                          );
                                        },
                                      ),
                                      titlesData: FlTitlesData(
                                        show: true,
                                        bottomTitles: AxisTitles(
                                          sideTitles: SideTitles(
                                            showTitles: true,
                                            reservedSize: 30,
                                            getTitlesWidget: bottomTitleWidgets,
                                            interval: 1,
                                          ),
                                        ),
                                        leftTitles: AxisTitles(
                                          sideTitles: SideTitles(
                                            showTitles: true,
                                            getTitlesWidget: leftTitleWidgets,
                                            reservedSize: 42,
                                            interval: 1,
                                          ),
                                        ),
                                        topTitles: AxisTitles(
                                          sideTitles: SideTitles(showTitles: false),
                                        ),
                                        rightTitles: AxisTitles(
                                          sideTitles: SideTitles(showTitles: false),
                                        ),
                                      ),
                                      borderData: FlBorderData(
                                        show: true,
                                        border: Border(
                                          bottom: BorderSide(color: Colors.grey[300]!,width: 1),
                                          top: BorderSide(color: Colors.grey[300]!,width: 1),
                                        ),
                                      ),
                                      minX: 0,
                                      maxX: 31,
                                      minY: min.toDouble(),
                                      maxY: max.toDouble(),
                                      lineBarsData: [
                                        LineChartBarData(
                                          spots: list.isEmpty?[]:list[choose].flspots,
                                          isCurved: true,
                                          color: Colors.red,
                                          barWidth: 4,
                                          isStrokeCapRound: true,
                                          dotData: FlDotData(
                                            show: false,
                                          ),
                                          belowBarData: BarAreaData(
                                            show: true,
                                            gradient: LinearGradient(
                                              colors: [
                                                ColorTween(begin: Colors.red, end:Colors.transparent)
                                                    .lerp(0.2)!
                                                    .withOpacity(0.1),
                                                ColorTween(begin: Colors.red, end: Colors.transparent)
                                                    .lerp(0.2)!
                                                    .withOpacity(0.1),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    )
                                ),
                              ),

`

**Comment by tudosxxx** [comment]
`AspectRatio(
                                aspectRatio: 1.7,
                                child: LineChart(
                                    LineChartData(
                                      lineTouchData: LineTouchData(
                                          enabled: true,
                                          touchTooltipData:LineTouchTooltipData(
                                            tooltipBgColor: Colors.black,
                                            getTooltipItems:(touchedSpots){
                                              return touchedSpots.map((LineBarSpot touchedSpot) {
                                                const textStyle = TextStyle(
                                                  color: Colors.white,
                                                  fontFamily: 'regular3',
                                                  fontSize: 14,
                                                );
                                                return LineTooltipItem(touchedSpot.y.toString(), textStyle);
                                              }).toList();
                                            }
                                          ),
                                      ),
                                      gridData: FlGridData(
                                        show: true,
                                        drawHorizontalLine: true,
                                        drawVerticalLine: true,
                                        verticalInterval: 10,
                                        horizontalInterval: 10,
                                        getDrawingVerticalLine: (value) {
                                          return FlLine(
                                            color: Colors.grey[300],
                                            strokeWidth: 1,
                                          );
                                        },
                                        getDrawingHorizontalLine: (value) {
                                          return FlLine(
                                            color: Colors.grey[300],
                                            strokeWidth: 1,
                                          );
                                        },
                                      ),
                                      titlesData: FlTitlesData(
                                        show: true,
                                        bottomTitles: AxisTitles(
                                          sideTitles: SideTitles(
                                            showTitles: true,
                                            reservedSize: 30,
                                            getTitlesWidget: bottomTitleWidgets,
                                            interval: 1,
                                          ),
                                        ),
                                        leftTitles: AxisTitles(
                                          sideTitles: SideTitles(
                                            showTitles: true,
                                            getTitlesWidget: leftTitleWidgets,
                                            reservedSize: 42,
                                            interval: 1,
                                          ),
                                        ),
                                        topTitles: AxisTitles(
                                          sideTitles: SideTitles(showTitles: false),
                                        ),
                                        rightTitles: AxisTitles(
                                          sideTitles: SideTitles(showTitles: false),
                                        ),
                                      ),
                                      borderData: FlBorderData(
                                        show: true,
                                        border: Border(
                                          bottom: BorderSide(color: Colors.grey[300]!,width: 1),
                                          top: BorderSide(color: Colors.grey[300]!,width: 1),
                                        ),
                                      ),
                                      minX: 0,
                                      maxX: 31,
                                      minY: min.toDouble(),
                                      maxY: max.toDouble(),
                                      lineBarsData: [
                                        LineChartBarData(
                                          spots: list.isEmpty?[]:list[choose].flspots,
                                          isCurved: true,
                                          color: Colors.red,
                                          barWidth: 4,
                                          isStrokeCapRound: true,
                                          dotData: FlDotData(
                                            show: false,
                                          ),
                                          belowBarData: BarAreaData(
                                            show: true,
                                            gradient: LinearGradient(
                                              colors: [
                                                ColorTween(begin: Colors.red, end:Colors.transparent)
                                                    .lerp(0.2)!
                                                    .withOpacity(0.1),
                                                ColorTween(begin: Colors.red, end: Colors.transparent)
                                                    .lerp(0.2)!
                                                    .withOpacity(0.1),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    )
                                ),
                              ),`

**Comment by imaNNeo** [comment]
You can customize the touch behavior. Start from [here](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/handle_touches.md). And read the sample codes
