### ISSUE TITLE
Please how do I achieve a pie chart with the following effect

### ISSUE THREAD

**Issue by THJLearn** [imaNNeo/fl_chart#1384]
![image](https://github.com/imaNNeo/fl_chart/assets/12946242/ad05f1b0-2647-4b88-9cda-88e9b9f17585)

饼状图的每一个item 如图中箭头指的地方，有圆角效果

Each item of the pie chart is pointed by the arrow in the figure, with a rounded corner effect

Thank you very much ！

**Comment by imaNNeo** [comment]
Duplicate #1175
