### ISSUE TITLE
BarChart isn't fit to its visible area

### ISSUE THREAD

**Issue by sownt** [imaNNeo/fl_chart#1388]
[`BarChartHelper`](https://github.com/imaNNeo/fl_chart/blob/master/lib/src/chart/bar_chart/bar_chart_helper.dart) always return `0.0` for `minY` value if all `fromY` values from `ChartData` is positive.

![Frame 2](https://github.com/imaNNeo/fl_chart/assets/44340502/7aae52fc-0eed-4c53-aa26-11c2e2a63b17)

**Comment by imaNNeo** [comment]
Oh, that's a bad bug that affects everything.
Thanks you for reporting btw.

**Comment by imaNNeo** [comment]
Fixed in [0.64.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.64.0)
