### ISSUE TITLE
Extend the prompt data display time

### ISSUE THREAD

**Issue by tudosxxx** [imaNNeo/fl_chart#1396]
TouchData will not be displayed when the finger is removed. Sometimes it is covered by fingers and I want to extend the display time. what do I do? For example, after the finger slides, it is still displayed for 2 seconds and then disappears

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=Wa0L9iYkSjc

**Comment by imaNNeo** [comment]
If you need exactly 2 seconds, you need to customize the touchCallback to implement your own logic.
But there is another solution to increase the `touchSpotThreshold` in [LineTouchData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/line_chart.md#linetouchdata-read-about-touch-handling)
