### ISSUE TITLE
Borken or compress Y-axis 

### ISSUE THREAD

**Issue by a1573595** [imaNNeo/fl_chart#1400]
Describe the feature
I searched for Issues and Discussions, but I didn't find a function about how to Break or compress Y-axis. How can I do it if the scale of the Y-axis is not the same?

Example
![Example](https://github.com/imaNNeo/fl_chart/assets/25738593/c54f2c5c-5edb-4778-8338-a93a1c9b198a)

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=Wa0L9iYkSjc

**Comment by imaNNeo** [comment]
We don't have this feature at this time. It is somehow related to #434 
Please put your sample there to have a sample in the main thread.

Thanks!
