### ISSUE TITLE
How to drag and drop two existing points to form a new line?

### ISSUE THREAD

**Issue by linhlc-agiletech** [imaNNeo/fl_chart#1406]
**Describe the solution you'd like**
I have an existing chart with a collection of dots. Now I want user can tap to a point, drag and drop it to second point to form a new line. Example like in video below.

https://github.com/imaNNeo/fl_chart/assets/135201039/8fb3db7f-9ed5-4bed-b334-bdcdd1ef46bd

**Describe alternatives you've considered**
I've posted a similar issue to syncfusion_chart team (you can check link below), and their workaround is tap 2 point each to draw a new line. It can draw a new line indeed, but it's not what I looking for. I need that user can drag and drop like in the video, not tap 2 point each.

**Additional context**
[Issue that I posted in syncfusion_chart team's github](https://github.com/syncfusion/flutter-widgets/issues/1285)

**Comment by le-liam-realestateanalytics** [comment]
Example video

https://github.com/imaNNeo/fl_chart/assets/136664117/468e28d0-0d4d-4363-a39f-034159afccf4

**Comment by imaNNeo** [comment]
I made a quick [gist](https://gist.github.com/imaNNeo/902de71f285fe29f8f0567a4fac0498c). I know it is not a perfectly clean way of doing this. But it works!

https://user-images.githubusercontent.com/7009300/262178600-ae5b5a6f-6364-40e1-949d-8bff7f4d7cca.mp4
