### ISSUE TITLE
LineChart is not rendered completely on iOS

### ISSUE THREAD

**Issue by cirediew** [imaNNeo/fl_chart#1410]
**Describe the bug**
The line chart is not rendered completely on iOS when there are over 2000+ spots.
This happens both on the iOS simulator and an iPhone 13. Android works fine.

**To Reproduce**

```dart
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';

class FlChartExampleChart extends StatelessWidget {
  const FlChartExampleChart({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('FL Chart'),
      ),
      body: SafeArea(
        child: LineChart(
          LineChartData(
            lineBarsData: [
              LineChartBarData(
                barWidth: 1.0,
                isStepLineChart: true,
                dotData: const FlDotData(show: false),
                spots: List.generate(
                  5000,
                  (index) => FlSpot(
                    index.toDouble(),
                    index.isEven ? 500 : 700,
                  ),
                ),
              ),
            ],
            minY: 100,
            maxY: 800
          ),
        ),
      ),
    );
  }
}

```

Using `isStepLineChart: true` will render around 3200 spots. Setting it to false will render around 2400 spots.

**Screenshots**
![Simulator Screenshot - iPhone 14 - 2023-08-03 at 14 32 38](https://github.com/imaNNeo/fl_chart/assets/9058616/86cbd4da-ac7c-4b15-816e-97cded051444)

**Versions**
 - which version of the Flutter are you using?
    `Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F82 darwin-arm64`
 - which version of the FlChart are you using?
    `fl_chart: ^0.63.0`

**Comment by ozzy1873** [comment]
I am also seeing incomplete renders on iOS.

**Comment by ozzy1873** [comment]
True, but it is not a fl_chart bug. We have to wait for Google to fix impeller. It would be interesting to know if your issue is also fixed by disabling impeller. If so, a bug report should be filed with Google.

https://docs.flutter.dev/perf/impeller
https://github.com/flutter/engine/blob/main/impeller/docs/faq.md

**Comment by ozzy1873** [comment]
This issue is for the same problem and has simple example code:
https://github.com/imaNNeo/fl_chart/issues/1342

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=Wa0L9iYkSjc

**Comment by cirediew** [comment]
It seems to be working as expected after upgrading to Flutter 3.13.1
