### ISSUE TITLE
RadarChart min value is always at first tick

### ISSUE THREAD

**Issue by ColinSchmale** [imaNNeo/fl_chart#1411]
Hey, thanks for creating this awesome plugin. 👍 

Unfortunately, there is a very serious error in the latest version.

Commit [fix radar chart tick point not scaling](https://github.com/imaNNeo/fl_chart/commit/c35539284fce4fcdadc5ad23872e95226d8760d8) of Version 0.62.0 broke the radar chart. The min value is completely wrong.

You can create a radar chart with three values like this to reproduce the problem.
The max value (100) is at 100% which is correct but the min value (90) is at the first tick instead.
It does not matter what you use as min value. 0, 1, 50, 90, 99. It's always at the first tick.
```
List<RawDataSet> rawDataSets() {
    return [
      RawDataSet(
        title: 'Fashion',
        color: widget.fashionColor,
        values: [
          100,
          90,
          90,
        ],
      ),
    ];
  }
  
  // Make the tick border visible so it's easier to see
  tickBorderData: BorderSide(color: Colors.green),
```

I've tried to fix the bug myself but I don't understand the code.
When you use 0 for the centerValue instead of getChartCenterValue, it seems to work.

It might be related to this issue: https://github.com/imaNNeo/fl_chart/issues/1351

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=Wa0L9iYkSjc

**Comment by imaNNeo** [comment]
Yes I think it is related to #1351 
I will close this one and let's continue it in the other thread.

Thanks!
