### ISSUE TITLE
Multi Coloured Line Chart

### ISSUE THREAD

**Issue by AymenXD** [imaNNeo/fl_chart#1412]
First of all, thank you for this great package.

I have a question concerning the line chart: Is there any possibility to change the color of the Line Chart or Below Line Chart based on some thresholds?

![multi_coloured_chart](https://github.com/imaNNeo/fl_chart/assets/41294956/32ffa52f-a3c5-4def-aa14-d78ff351d8ac)

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=Wa0L9iYkSjc

**Comment by imaNNeo** [comment]
You might need to use `rodStackItem` in [BarChartRodData](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/bar_chart.md#barchartroddata) class to achieve that.

##### Sample 4 ([Source Code](https://github.com/imaNNeo/fl_chart/blob/master/example/lib/presentation/samples/bar/bar_chart_sample4.dart))
<img src="https://github.com/imaNNeo/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_4.png" width="300" >
