### ISSUE TITLE
How to control the thickness of the pie chart

### ISSUE THREAD

**Issue by jonas-martinez** [imaNNeo/fl_chart#1414]
> Did you get any solution **to control the thickness of the pie chart**. ??

_Originally posted by @4nkitpatel in https://github.com/imaNNeo/fl_chart/issues/179#issuecomment-860190250_

Hi,

I'm opening this issue because I cannot figure out how to control the thickness of the pie chart. It seems that when creating a pie chart inside of a small container, you cannot control the space in the center of the pie chart. You could use the centerSpaceRadius but it just makes the pie chart bigger and overflow off the container.

How can I control the thickness of the pie chart so that it looks more like this ? 
![image](https://user-images.githubusercontent.com/36544012/259998831-091fea96-6cf7-4ae0-bfb0-bae8e005fda5.png) (this screenshot is taken from the [pie_chart](https://pub.dev/packages/pie_chart) library)

Thank you

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=Wa0L9iYkSjc

**Comment by imaNNeo** [comment]
There is no direct thickness function. But you can achieve that by changing `centerSpaceRadius` and ` sections.radius` properties.
Take a look at the below sample ([source code is here](https://gist.github.com/imaNNeo/af6e113f86f8a5c9dbe0b66ede34d116)):

https://user-images.githubusercontent.com/7009300/269442420-9bae713a-043f-486d-85bd-b078450225ed.mov
