### ISSUE TITLE
Support an additional Y axis on the right of the line chart

### ISSUE THREAD

**Issue by bigbang489** [imaNNeo/fl_chart#1417]
Assume that we have 2 line charts. The left axis showcases S&P 500 index, while the right axis features the second line, representing the P/E ratio, see the below image:
![image](https://github.com/imaNNeo/fl_chart/assets/29498440/d5482139-9c58-4479-bcf5-2998ba986ac0)

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=Wa0L9iYkSjc

**Comment by obiwan007** [comment]
Would be really nice to have multi-y axis support for line charts.

**Comment by mivoligo** [comment]
Looks like a duplicate of #429

**Comment by imaNNeo** [comment]
@mivoligo YOu're right. Thanks!
Please follow the #429 issue
