### ISSUE TITLE
belowBarData not working in ios

### ISSUE THREAD

**Issue by movilixaTecnologia** [imaNNeo/fl_chart#1427]
**Describe the bug**
belowBarData in BarAreaData is not working for ios in flutter 13.3

**To Reproduce**
void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    List<FlSpot> spots = [
      const FlSpot(0, 1),
      const FlSpot(1, 2),
      const FlSpot(2, 3),
      const FlSpot(3, 4),
      const FlSpot(4, 5),
      const FlSpot(5, 6),
      const FlSpot(6, 3),
      const FlSpot(7, 8),
      const FlSpot(8, 9),
      const FlSpot(9, 10),
    ];
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: SizedBox(
            width: double.infinity,
            height: 190,
            child: LineChart(
              LineChartData(
                lineBarsData: [
                  LineChartBarData(
                    spots: spots,
                    isCurved: false,
                    color: Colors.black,
                    barWidth: 1,
                    isStrokeCapRound: true,
                    belowBarData: BarAreaData(
                      show: true,
                      color: Colors.green.withOpacity(0.3),
                      cutOffY: 5,
                      applyCutOffY: true,
                    ),
                    aboveBarData: BarAreaData(
                      show: true,
                      color: Colors.red.withOpacity(0.6),
                      cutOffY: 5,
                      applyCutOffY: true,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

**Screenshots**

![Screenshot_1692996282](https://github.com/imaNNeo/fl_chart/assets/138793902/bf9cc3cd-f97b-4a28-bd91-be07d34a759d)

![Simulator Screenshot - iPhone 14 Pro - 2023-08-25 at 15 44 45](https://github.com/imaNNeo/fl_chart/assets/138793902/d5b249ac-48dc-4bc3-8c06-78411bba7d7c)

**Versions**
 - Flutter 3.13.3
 - fl_chart 0.63.0

**Comment by beerline** [comment]
Same for me
Flutter: 3.13.6
fl_chart: 0.63.0

**Comment by imaNNeo** [comment]
It might be the [impeller](https://docs.flutter.dev/perf/impeller) issue

**Comment by veloce** [comment]
Do you know which impeller issue specifically? And if there is a workaround? I might try to tackle this, thanks!

**Comment by imaNNeo** [comment]
I'm not sure, can you please test it with and without the Impeller?

**Comment by veloce** [comment]
I did and I confirm it does work without impeller.

**Comment by lauroboeni** [comment]
> I did and I confirm it does work without impeller.

So the only workaround is to disable impeller for the whole app?

**Comment by imaNNeo** [comment]
> > I did and I confirm it does work without impeller.
> 
> So the only workaround is to disable impeller for the whole app?

Yes, I think. Or I would appreciate it if someone take a look to fix it.

**Comment by lauroboeni** [comment]
@movilixaTecnologia which version contains the fix?
