### ISSUE TITLE
Tooltip overflows when it's close to the container edge

### ISSUE THREAD

**Issue by JGeek00** [imaNNeo/fl_chart#1432]
When the tooltip is close to the left/right side of the chart container, it overflows to the side. It would be great if instead of overflowing, when you touch a point that is close to the edge, the tooltip would appear close to the edge but without overflowing.

<img width="788" alt="image" src="https://github.com/imaNNeo/fl_chart/assets/47545344/b38e8651-50d8-486e-8693-7f1eed6cdc61">

fl_chart: 0.62.0
flutter: 3.13.2

**Comment by techouse** [comment]
You need to configure your tooltip to use `fitInsideHorizontally: true`, i.e.

```dart
LineChart(
	LineChartData(
		lineTouchData: LineTouchData(
			touchTooltipData: LineTouchTooltipData(
				fitInsideHorizontally: true, // <-- this
				// stuff ...
			)
			// stuff ...
		)
		// stuff ...
	)
	// stuff ...
);
```

**Comment by JGeek00** [comment]
That solved my issue. Thank you.
