### ISSUE TITLE
Provide context to bottomTitles in barchart

### ISSUE THREAD

**Issue by milindgoel15** [imaNNeo/fl_chart#1440]
**Is your feature request relasted to a problem? Please describe.**
Not much of a problem but there's no way to localise bottom titles for barchart at least. Say we provided custom strings for each bar so we cannot localize them right now because localization requires context to be passed and currently the getTitlesWidget doesn't accept buildContext to be passed.

```dart
bottomTitles: AxisTitles(
                      sideTitles: SideTitles(
                        showTitles: true,
                        getTitlesWidget: getBottomTitles,
                        reservedSize: 30,
                      ),
                      // axisNameWidget: Text('Types of Levels'),
                    ),
                    
  where getTitlesWidget accepts Widget Function(double, TitleMeta) getTitlesWidget
```

**Describe the solution you'd like**
Provide buildContext in the constructor so that it can be passed to text.

**Describe alternatives you've considered**
n/a

**Comment by a1573595** [comment]
> **Is your feature request relasted to a problem? Please describe.** Not much of a problem but there's no way to localise bottom titles for barchart at least. Say we provided custom strings for each bar so we cannot localize them right now because localization requires context to be passed and currently the getTitlesWidget doesn't accept buildContext to be passed.
> 
> ```dart
> bottomTitles: AxisTitles(
>                       sideTitles: SideTitles(
>                         showTitles: true,
>                         getTitlesWidget: getBottomTitles,
>                         reservedSize: 30,
>                       ),
>                       // axisNameWidget: Text('Types of Levels'),
>                     ),
>                     
>   where getTitlesWidget accepts Widget Function(double, TitleMeta) getTitlesWidget
> ```
> 
> **Describe the solution you'd like** Provide buildContext in the constructor so that it can be passed to text.
> 
> **Describe alternatives you've considered** n/a

Try Builder.

```dart=
SideTitleWidget(
              axisSide: meta.axisSide,
              child: Builder(
                builder: (context) => Text(
                  value.toStringAsFixed(0),
                  style: Theme.of(context).textTheme.bodyMedium,
                ),
              ),
            ),
```

**Comment by milindgoel15** [comment]
> Try Builder

thanks. it helped
