### ISSUE TITLE
Unable to show tooltip for same x value with different y values in line chart

### ISSUE THREAD

**Issue by VGT-Tushar** [imaNNeo/fl_chart#1441]
**Describe the bug**
In my line chart i have multiple spots with same x values with different y values like (1,10), (1,20)
 but tooltip is shown only for (1,10) even if I clicked on (1,20) tooltip is shown for (1,10).
**To Reproduce**
           Container(
                          height: MediaQuery.of(context).size.height * 0.5,
                          width: MediaQuery.of(context).size.width,
                          margin: EdgeInsets.only(right: 50),
                          child: LineChart(
                            LineChartData(
                              lineBarsData: [
                                LineChartBarData(
                                  spots: [
                                       FlSpot(1,10),
                                       FlSpot(1,20),
                                       FlSpot(1,30),
                                       FlSpot(1,40)
                                         ],
                                  color: Colors.blueAccent,
                              ],
                            ),
                          ),
                        ),

**Screenshots**
![Screenshot_1695034828](https://github.com/imaNNeo/fl_chart/assets/131458510/c6a27bc5-efa9-4821-ac6d-caa5c11df8db)

**Versions**
 - which version of the Flutter are you using?
    Flutter 3.10.6

 - which version of the FlChart are you using?
     fl_chart: ^0.61.0

**Comment by imaNNeo** [comment]
You can do that, check our [first line chart sample](https://app.flchart.dev/#/line)
