### ISSUE TITLE
[Help] - how can we plot chart point from where the data is available and keep remaining space empty

### ISSUE THREAD

**Issue by keiraperks** [imaNNeo/fl_chart#1443]
** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.

**Describe the bug**
- Attached a reference image.

**To Reproduce**
Provide us a completely reproducible code (contains the main function) in a `main.dart` file, it helps us to find the bug immediately.

**Screenshots**

<img width="714" alt="Screenshot 2023-09-19 at 4 42 12 PM" src="https://github.com/imaNNeo/fl_chart/assets/55679951/bbfb03a3-af2b-406d-b59c-397127c843d6">

**Versions**
 - which version of the Flutter are you using? - 3.10.5
 - which version of the FlChart are you using? - 0.61.0

**Comment by imaNNeo** [comment]
You can set a `minX` with a lower value than your actual minX (based on your data)
