### ISSUE TITLE
Line chart is not rending properly when X-axis is time stamp. 

### ISSUE THREAD

**Issue by Sumit258000** [imaNNeo/fl_chart#1452]
Recently I came across a situation in which I had to draw a Line chart with DateTime on the x-axis.As x-axis is not accepting string as value my chart looks dirty if there is any 1 month gap. I tried different solutions and issues present across the repository:

- [Having custom interval.](https://github.com/imaNNeo/fl_chart/issues/357)
- `[Converting Date Time to timestamp](https://github.com/imaNNeo/fl_chart/issues/438#issuecomment-1706238545)`
but none of the above answers works.
**Actual Result**
![image](https://github.com/imaNNeo/fl_chart/assets/134265081/ecba39f6-5a42-4947-8c83-c9db37249c73)

**Expected Result**
![image](https://github.com/imaNNeo/fl_chart/assets/134265081/5644715d-cf5c-427f-bdbf-626aa3d0fd84)

The expected result is achieved by using [react-chartjs](https://react-chartjs-2.js.org/)

I am trying [following json](http://jsonblob.com/1158756531969056768) to plot chart between **score** and **time**
@imaNNeo

**Comment by imaNNeo** [comment]
Please followup this issue: #438

**Comment by Sumit258000** [comment]
Don't think my issue is related to https://github.com/imaNNeo/fl_chart/issues/438 because I am looking for some support in which I can pass `string` in the x-axis something like [this](https://help.syncfusion.com/flutter/cartesian-charts/axis-types#category-axis).

**Comment by imaNNeo** [comment]
> Don't think my issue is related to #438 because I am looking for some support in which I can pass `string` in the x-axis something like [this](https://help.syncfusion.com/flutter/cartesian-charts/axis-types#category-axis).

Sorry but I couldn't understand what exactly is the issue
