### ISSUE TITLE
FL_chart: How to display correctly the values inside the tooltip

### ISSUE THREAD

**Issue by solrac3f** [imaNNeo/fl_chart#1460]
I am struggling a lot to display the values in the tooltip correctly.

I'm using this package https://pub.dev/packages/fl_chart. There is the possibility of when you move the mouse over a line of the graph to show a tooltip with the data but of all the lines on the graph. I have 4 data that i want to display on the Tooltip. Max, Min, Avg and Count.

At this moment i get displayd as follows:
![GXLKi](https://github.com/imaNNeo/fl_chart/assets/81438502/cdaacb05-751f-49bb-bcea-e92b34456ecb)

I would need that the Tooltip would display the data as follows:
![Untitled](https://github.com/imaNNeo/fl_chart/assets/81438502/17810463-af68-4f51-96e1-5e98ef1a343f)

Follows the code:
`                    touchTooltipData: LineTouchTooltipData(
                      getTooltipItems: (List<LineBarSpot> touchedBarSpots) {
                        final tooltips = <LineTooltipItem>[];

                        for (final barSpot in touchedBarSpots) {
                          final flSpot = barSpot.bar.spots[barSpot.spotIndex];
                          final max = flSpot.y;
                          final min = flSpot.y;
                          final avg = flSpot.y;
                          final count = flSpot.x.toInt();

                          final tooltipText =
                              "Max: ${max.toStringAsFixed(2)}\nMin: ${min.toStringAsFixed(2)}\nAvg: ${avg.toStringAsFixed(2)}\nCount: $count";
                          tooltips.add(LineTooltipItem(tooltipText, const TextStyle(fontSize: 12)));
                        }

                        return tooltips;
                      },
                      tooltipBgColor: const Color(0xFFC0AAAA),
                      tooltipPadding: const EdgeInsets.symmetric(horizontal: 6, vertical: 3),
                    ),`
Thanks in advance for some help

**Comment by imaNNeo** [comment]
You can fill fill `null` on the returning tooltips list for the items that you don't want to show them.
For example if you want to show the only first item, you can use the below code:

```dart
return touchedSpots.asMap().entries.map((entry) {
  final index = entry.key;
  final touchedSpot = entry.value;
  if (index != 0) {
    return null;
  }
  final textStyle = TextStyle(
    color: touchedSpot.bar.gradient?.colors.first ??
        touchedSpot.bar.color ??
        Colors.blueGrey,
    fontWeight: FontWeight.bold,
    fontSize: 14,
  );
  return LineTooltipItem(touchedSpot.y.toString(), textStyle);
}).toList();
```
