### ISSUE TITLE
Enhanced LineChart Interaction: Dynamic Point Display and Removal

### ISSUE THREAD

**Issue by fabiototh** [imaNNeo/fl_chart#1461]
When a user clicks on the LineChart, the specific point clicked on is displayed using the lineTouchData, even if the user doesn't continue holding on that point. Is it possible that when a user clicks on the LineChart, the specific point clicked on is displayed using the lineTouchData, even if the user doesn't continue holding on that point?

If the user clicks on the chart again, the previously displayed point is removed, leaving the chart without any lineTouchData being shown. Additionally, if the user clicks, holds, and drags across the LineChart, each point is displayed as they move. Upon releasing, the lineTouchData will continue to display the last point where the user stopped?

LineChart X-axis Feedback: Haptic Vibration on Point Transition: For every movement of the lineTouchData on the X-axis, is it possible to add a slight vibration so the user feels when they transition from one point to another?

**Comment by imaNNeo** [comment]
Generally, you can disable `handleBuiltInTouches` and override the `touchCallback` to implement your own logic. Then you can do whatever you want.
For example, I've implemented something similar in BarChart (some concepts are the same and similar). You can take a look.
 
[code is here](https://gist.github.com/imaNNeo/bce3f0169ff3fd6c3f137cdeb5005c0e)

https://user-images.githubusercontent.com/7009300/156784816-53f95dd9-f387-4600-8a92-d05b1aeea3da.mov
