### ISSUE TITLE
BackgroundBarChartRodData with negative values broke in 0.64.0

### ISSUE THREAD

**Issue by bradrushworth** [imaNNeo/fl_chart#1470]
**Describe the bug**
Version 0.64.0 changed the behaviour of BackgroundBarChartRodData so that the entire value cannot be seen anymore. Seems to work ok for positive values, but doesn't work for negative values.

In the example below, the yellow bars are the Background values.

**To Reproduce**
Provide us a completely reproducible code (contains the main function) in a `main.dart` file, it helps us to find the bug immediately.

https://github.com/bradrushworth/amber/blob/e5229dd8a7a35bcb1c780c21da9536cb9ab263dc/lib/bar_chart.dart#L467C48-L467C48

**Screenshots**
Behaviour of version 0.63.0
![image](https://github.com/imaNNeo/fl_chart/assets/859577/4643617d-5a09-4ded-b338-e8d292af3308)

Behaviour of version 0.64.0
![image](https://github.com/imaNNeo/fl_chart/assets/859577/0240ca81-ef22-4e44-8718-b04958913e5b)

**Versions**
Flutter 3.13.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2524052335 (7 weeks ago) • 2023-09-06 14:32:31 -0700
Engine • revision b8d35810e9
Tools • Dart 3.1.1 • DevTools 2.25.0

**Comment by imaNNeo** [comment]
Oh, you're right. That was a mistake

**Comment by bradrushworth** [comment]
Can confirm the branch version works correctly... Thanks.

**Comment by imaNNeo** [comment]
Oh great! Thanks for testing it.
It will be landed in a release soon 🚀

**Comment by imaNNeo** [comment]
Landed in [0.65.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.65.0)
Check it out!
