### ISSUE TITLE
How to set the interval between each line chart, rather than the entire LineChart.

### ISSUE THREAD

**Issue by zhaoxiuyu** [imaNNeo/fl_chart#1475]
如何设置折线图每个之间的间隔，而不是平均占满整个LineChart。

How to set the interval between each line chart, rather than the entire LineChart.

as shown in the figure
![1698918887239](https://github.com/imaNNeo/fl_chart/assets/16554580/45c9db10-61ea-4756-8574-d4c07843fbb2)

**Comment by imaNNeo** [comment]
Hi, I didn't understand what you mean. Can you explain it more?

**Comment by zhaoxiuyu** [comment]
@imaNNeo 
I'm sorry, it's my problem.
Can you use fl_chart to achieve the above renderings?  Is there a Demo

**Comment by imaNNeo** [comment]
No problem. 
Yes, you can achieve that, but what part is challenging for you?

**Comment by kauemurakami** [comment]
For those who still need the answer in 2024:

```dart
 LineChartData(
 ...
  titlesData: FlTitlesData(
                  bottomTitles: AxisTitles(
                    sideTitles: SideTitles(showTitles: false, interval: 1),
                  ),
                  rightTitles: AxisTitles(
                    sideTitles: SideTitles(
                      showTitles: false,
                    ),
                  ),
                  topTitles: AxisTitles(
                    sideTitles: SideTitles(
                      showTitles: false,
                    ),
                  ),
                ),
 
 ...)

```
Use  ```interval``` param
