### ISSUE TITLE
FL Chart Errors

### ISSUE THREAD

**Issue by some1onLSD** [imaNNeo/fl_chart#1492]
Hello,
I use fl_chart v0.45.1 and this code snippets work perfectly but when I update to a version after 0.45.1 it gives multiple errors.

```
FlTitlesData(
                  show: true,
                  rightTitles: SideTitles(showTitles: false),
                  topTitles: SideTitles(showTitles: false),
                  leftTitles: SideTitles(showTitles: false),
                  bottomTitles: SideTitles(
                    rotateAngle: Responsive.isMobile(context) ? 45 : 0,
                    showTitles: true,
                    getTextStyles: (context, value) => TextStyle(
                      color: Styles.defaultLightGreyColor,
                      fontWeight: FontWeight.bold,
                      fontSize: 12,
                    ),
                    getTitles: (double value) {
                      switch (value.toInt()) {
                        case 0:
                          return 'Mon';
                        case 1:
                          return 'Tue';
                        case 2:
                          return 'Wed';
                        case 3:
                          return 'Thu';
                        case 4:
                          return 'Fri';
                        case 5:
                          return 'Sat';
                        case 6:
                          return 'Sun';
                        default:
                          return '';
                      }
                    },
                  ),
                ),
```
and :

```
  static BarChartGroupData makeGroupData(
      int x, double y1, Color barColor, double width) {
    return BarChartGroupData(
      barsSpace: 1,
      x: x,
      barRods: [
        BarChartRodData(
          y: y1,
          colors: [barColor],
          width: width,
          borderRadius: const BorderRadius.only(
            topLeft: Radius.circular(20),
            topRight: Radius.circular(20),
          ),
        ),
      ],
    );
```

the errors outputs:
-The named parameter 'rotateAngle' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'rotateAngle'.
-The named parameter 'getTitles' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'getTitles'.
-The named parameter 'getTextStyles' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'getTextStyles'.
-The argument type 'SideTitles' can't be assigned to the parameter type 'AxisTitles'.
-The named parameter 'colors' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'colors'.
-The named parameter 'toY' is required, but there's no corresponding argument.
Try adding the required argument.
![err](https://github.com/imaNNeo/fl_chart/assets/74503778/f74ebba3-6531-4ead-bc41-f4d21a8cffa4)

**Comment by imaNNeo** [comment]
Hi, you need to read the [changelog](https://pub.dev/packages/fl_chart/changelog) and update your code base when we have breaking changes.
For example, I'm pretty sure that we had some breaking changes on [0.46.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.46.0) and [0.50.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.50.0)
