### ISSUE TITLE
LineChart with multiple lines: Get single point on hovering/tapping a line

### ISSUE THREAD

**Issue by pamtbaau** [imaNNeo/fl_chart#1510]
I've read the docs, searched the web and issues here but haven't found a solution yet...

When hovering lines in a LineChart with multiple lines, I always get a tooltip with values for each line at a certain Y value. What I want is to show a tooltip for only the line the mouse is hovering over or being tapped.

In a stacked BarChart however, in onTouchCallback the BarTouchResponse contains a single BarTouchedSpot with a touchedBarGroupIndex and touchedStackItemIndex. I can then use these indexes to show only a single value in the tooltip.

**Describe the solution you'd like**
I would line the LineTouchResponse:
- To have a single TouchLineBarSpot with properties like the touchedLineGroupIndex/touchedStackItemIndex.
- Or adding properties touchedLineGroupIndex/touchedStackItemIndex to the LineTouchResponse itself.

**Comment by MonirDev** [comment]
Facing same issue. Showing Both data combinedly on same tooltip and tooltip position also same

**Comment by pamtbaau** [comment]
Curious if any progress can be shared... Is feature considered, or 'won't implement'?

**Comment by imaNNeo** [comment]
Does [this answer](https://github.com/imaNNeo/fl_chart/issues/1585#issuecomment-1970033204) help?

**Comment by pamtbaau** [comment]
@imaNNeo, Thanks for your follow-up. 

I'm sorry to say that I got curious to alternatives in the meantime and I've just finished migrating the other day. Which by the way doesn't mean FL_Charts isn't a great product... It is!

**Comment by imaNNeo** [comment]
> @imaNNeo, Thanks for your follow-up.
> 
> I'm sorry to say that I got curious to alternatives in the meantime and I've just finished migrating the other day. Which by the way doesn't mean FL_Charts isn't a great product... It is!

No worries, Thanks for letting me know.
I will do my best to make this library better every day.
