### ISSUE TITLE
Disable tooltip values auto-sorting

### ISSUE THREAD

**Issue by PLynx01** [imaNNeo/fl_chart#1513]
I have got a problem with tooltip configuration. My chart contains multiple lines that may cross with each other. I would like the tooltip numbers to be displayed with the order of LineChartBarData, not sorted in a descending way. 

Is there any solution to achieve this? Could you help me?

**Comment by PLynx01** [comment]
> Can you explain it more?
> What do you expect to have instead of the below image?
> <img width="457" alt="image" src="https://github.com/imaNNeo/fl_chart/assets/7009300/010435f5-30cb-4877-a3df-38c73b012900">
> 

There is no need to. I solved it by getting an value by using FlSpot data array with touchedSpot as index.

**Comment by imaNNeo** [comment]
Nice. Thanks for letting me know!
Enjoy charting!
