### ISSUE TITLE
No Gradient for VerticalLine and HorizontalLine

### ISSUE THREAD

**Issue by sethgillett** [imaNNeo/fl_chart#1525]
On fl_chart v0.65.0, the `FlLine` constructor contains an argument for a gradient, however the `VerticalLine` and `HorizontalLine` classes which extend it do not allow passing a gradient.

**Comment by imaNNeo** [comment]
Added in [0.66.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.66.0)
