### ISSUE TITLE
Pie chart sections all black iff one sections was once 100% (360 degrees)

### ISSUE THREAD

**Issue by buchen** [imaNNeo/fl_chart#1538]
**Problem**

If the chart once contains one section that takes up 100%, then after an update, pie slices will all be black.

**To Reproduce**

* Create a chart with one PieChartSectionData that represents 100 percent
* Then update the chart with multiple pie charts (say: two sections with each 50 percent)
* The color of the slices of the pie chart will be black

**Version**
0.66.0

**Potential root cause**

With change 68cf161f2623cedda2bf1b51bef758cf62beb812, the ```blendMode``` is set to ```BlendMode.srcOut``` on the ```_sectionPaint``` if there is a slice that takes up 100%. Later, if there are multiple slices, the ```drawSection``` is using the same ```_sectionPaint``` with the altered ```blendMode```.

I can confirm that the following code fixes the problem:

```dart

 void drawSection(
    PieChartSectionData section,
    Path sectionPath,
    CanvasWrapper canvasWrapper,
  ) {
    _sectionPaint
      ..setColorOrGradient(
        section.color,
        section.gradient,
        sectionPath.getBounds(),
      )
      ..blendMode = BlendMode.srcOver       <==== set blend mode to srcOver
      ..style = PaintingStyle.fill;
    canvasWrapper.drawPath(sectionPath, _sectionPaint);
  }

```

**Comment by owellnitz** [comment]
I have the same problem! Any solutions for this?

**Comment by shaynec25** [comment]
same issue here

**Comment by tattuu** [comment]
same issue here

**Comment by imaNNeo** [comment]
Yes, it is related to the code that you mentioned. 
Thanks for your detailed issue.

The hotfix is landed on the `main` branch.
Stay tuned for a hotfix
