### ISSUE TITLE
Manage z-index for Scatter Chart

### ISSUE THREAD

**Issue by vbaulac** [imaNNeo/fl_chart#1545]
Hi.

It would be very nice to be able to manage a z-index in the Scatter plot. I have a lot of point in my scatter plot, and they do not have the same color. And some are more important than others. I'd like them to be on front, so they are not hidden by others.

Current hack would probably be to change the order of the array of my Spots, but it is an hack.

Having a z-index property, CSS-style, would be super.

Thanks for this awesome lib !

Victor

**Comment by hareendranmg** [comment]
Hi @vbaulac , Did you found any solution?

**Comment by imaNNeo** [comment]
It's a good starting point for contributing, you can just read the [guideline](https://github.com/imaNNeo/fl_chart/blob/main/CONTRIBUTING.md) and open your PR.
We can add a property (for example called `renderPriority` which is null by default) here:
https://github.com/imaNNeo/fl_chart/blob/11d13a78e6a134aa0cfdcd8dfa88dceaf79a4033/lib/src/chart/scatter_chart/scatter_chart_data.dart#L189-L204

Then when rendering it, you can sort them by the `renderPriority` if any point has this property.

**Comment by mitulagr2** [comment]
I can take this if you'd like!

**Comment by imaNNeo** [comment]
> I can take this if you'd like!
Yes, that would be nice!

**Comment by imaNNeo** [comment]
This feature has just been added in [0.70.1](https://github.com/imaNNeo/fl_chart/releases/tag/0.70.1). Please take a look!
