### ISSUE TITLE
Memory clear?

### ISSUE THREAD

**Issue by AndroidDesigner** [imaNNeo/fl_chart#1552]
Hello.
I'm using this package on a linux-based app.
I'm loading a data list (size of elements is 500K) and wanna show it on the LineChart, but when close the screen, data is not cleared from the memory!
I checked my code and found the problem is due to the package. Because when i load data from database and don't show in the LineChart, memory is fine, while showing data in LineChart fills memory and clearing data in my statefulWidget (in dispose) does not affect on filled memory)
why?
what is the solution?

**Comment by imaNNeo** [comment]
It is related to the issue that you already wrote a comment here: #1106
I will fix it with high priority.
