### ISSUE TITLE
Unsupported operation: Platform._environment

### ISSUE THREAD

**Issue by Rexios80** [imaNNeo/fl_chart#1565]
https://github.com/imaNNeo/fl_chart/blame/4b144a03d14b750aea76001f763442eff8044c69/lib/src/chart/line_chart/line_chart_data.dart#L13

**Comment by Rexios80** [comment]
This line throws an exception on web

**Comment by Rexios80** [comment]
Should probably retract that version

**Comment by Sernrbia** [comment]
I have the same issue, on mobile it works perfectly but it fails on Chrome. Tested on latest Windows 10 and latest MacOS

**Comment by uberchilly** [comment]
![image](https://github.com/imaNNeo/fl_chart/assets/5727941/8718d75f-04c4-4755-a2b8-99d7777ea312)

**Comment by MODE83-PROJET-DEV** [comment]
same problem, solutions?

**Comment by ebutterfly** [comment]
I'm getting the same "Unsupported operation: Platform._environment" exception on Web with 0.66.1, making the latest version unusable on Web. If I downgrade back to 0.65.0, then fl_chart works again on Web.

**Comment by imaNNeo** [comment]
Yes, that was my mistake.
Thanks for letting me know and sorry for the delay.
It is already merged. We will have a new version soon

**Comment by MODE83-PROJET-DEV** [comment]
Thanks :) 👍
