### ISSUE TITLE
 Unsupported operation: Platform._environment

### ISSUE THREAD

**Issue by pratikNavapara009** [imaNNeo/fl_chart#1566]
** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.

**Describe the bug**

**To Reproduce**
Provide us a completely reproducible code (contains the main function) in a `main.dart` file, it helps us to find the bug immediately.

**Screenshots**
If applicable, add screenshots, or videoshots to help explain your problem.

**Versions**
 - which version of the Flutter are you using?
 - which version of the FlChart are you using?

**Comment by imaNNeo** [comment]
Please provide more information and don't send the default template as the issue description.

**Comment by NotTsunami** [comment]
Duplicate of #1565
