### ISSUE TITLE
How can I show a label VerticalLineLabel in vertical ?

### ISSUE THREAD

**Issue by minh-yuzu** [imaNNeo/fl_chart#1574]
Hello, i want to show a 'Accumulation' label from VerticalLineLabel in vertical as the image below. Could you please give me some ideals ?

<img width="239" alt="Screenshot 2024-01-30 at 11 11 19" src="https://github.com/imaNNeo/fl_chart/assets/158155259/75bb5d83-5e8a-428c-8b93-0eb9e8296164">

**Comment by imaNNeo** [comment]
Added `direction` property to the [HorizontalLineLabel](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/base_chart.md#horizontallinelabel) in [0.67.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.67.0)
Don't forget to read the [migration guide](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/migration_guides/0.67.0/MIGRATION_00_67_00.md) carefully
