### ISSUE TITLE
Scroll the line chart horizontally and add a custom yAxis.

### ISSUE THREAD

**Issue by lvmaoya** [imaNNeo/fl_chart#1575]
Because the line chart cannot be scrolled,I wrapped it with a SingleChildScrollView component. 
However, it created a new issue where the unit scale values of the y-axis are always displayed at the far left or far right. 
So, I customized a Column component to stack it and display the unit values, but I am having trouble accurately positioning it. 
Do you have any suggestions?

I am using the latest version.

![57CD725EF08C6B1687A83B545FB93A8D](https://github.com/imaNNeo/fl_chart/assets/89346430/109660d5-a612-4c28-9f1d-de945149f068)

**Comment by imaNNeo** [comment]
Please follow #71 and mention your issue there. 
There are already some solutions by people, also I'm working to implement it internally.
