### ISSUE TITLE
How can I make the tooltips to show individually for each point when adding two line charts to the same chart? Currently, the tooltips are displaying in the same tooltip for both line charts

### ISSUE THREAD

**Issue by MonirDev** [imaNNeo/fl_chart#1585]
**Describe the bug**
How can I make the tooltips to show individually for each point when adding two line charts to the same chart? Currently, the tooltips are displaying in the same tooltip for both line charts

**To Reproduce**

//LineChart widget
  LineChartData mainData() {
    return LineChartData(
      lineTouchData: _tooltipWidget(),
      gridData: FlGridData(
        show: true,
        drawVerticalLine: false,
        drawHorizontalLine: true,
        horizontalInterval: 20000,
        verticalInterval: 1,
        getDrawingHorizontalLine: (double value) {
          return const FlLine(
            color: AppColors.black,
            strokeWidth: 1,
          );
        },
      ),
      titlesData: titleData(),
      borderData: FlBorderData(
        show: true,
        border: const Border.symmetric(
          horizontal: BorderSide(
            color: AppColors.black,
            width: 1,
          ),
        ),
      ),
      minX: 0,
      minY: -80000,
      maxY: 20000,
      lineBarsData: <LineChartBarData>[
        lineChartBarWidget(grData, AppColors.blue),
        lineChartBarWidget(irData, AppColors.primaryColor),
      ],
    );
  }

//tooltip widget
  LineTouchData _tooltipWidget() {
    return LineTouchData(
      getTouchedSpotIndicator:
          (LineChartBarData barData, List<int> spotIndexes) {
        return spotIndexes.map((int spotIndex) {
          return const TouchedSpotIndicatorData(
            FlLine(color: AppColors.transparent, strokeWidth: 10),
            FlDotData(
              show: true,
            ),
          );
        }).toList();
      },
      touchTooltipData: LineTouchTooltipData(
        tooltipBgColor: AppColors.black,
        tooltipPadding: const EdgeInsets.all(5),
        tooltipMargin: 10,
        getTooltipItems: (List<LineBarSpot> touchedBarSpots) {
          return touchedBarSpots.map((LineBarSpot barSpot) {
            final LineBarSpot flSpot = barSpot;
            String value = convertToFormattedUnits(flSpot.y.toString());

            if (barSpot.barIndex == 0) {
              // print("GR $value");
              return LineTooltipItem(
                'GR: $value',
                const TextStyle(
                    color: AppColors.white,
                    fontWeight: FontWeight.bold,
                    fontSize: 14),
              );
            } else {
              // print("IR $value");
              return LineTooltipItem(
                'IR: $value',
                const TextStyle(
                    color: AppColors.white,
                    fontWeight: FontWeight.bold,
                    fontSize: 14),
              );
            }
          }).toList();
        },
      ),
      touchCallback: (FlTouchEvent val, LineTouchResponse? touchResponse) {},
      handleBuiltInTouches: true,
    );
  }

**Screenshots**
![image](https://github.com/imaNNeo/fl_chart/assets/59523027/c2dbc479-d99d-4355-a796-fc1c392d0bd1)

**Versions**
 - 0.66.1

**Comment by imaNNeo** [comment]
Yes, you can. The default behaviour only considers the xAxis distance to find the touched points.
You can override the LineTouchData.distanceCalculator method to consider both xAxis and yAxis (or any custom logic that you can think about).
Take a look at the below code:

```
lineTouchData: LineTouchData(
  distanceCalculator: (Offset touchPoint, Offset spotPixelCoordinates) {
    final diffX = (touchPoint.dx - spotPixelCoordinates.dx).abs(); // This is the default calculation
    final diffY = (touchPoint.dy - spotPixelCoordinates.dy).abs(); // We add diffY to add with diffX and return it
    return diffX + diffY;
  },
),
```
