### ISSUE TITLE
Show mixed data group types in a single line chart

### ISSUE THREAD

**Issue by andrespd99** [imaNNeo/fl_chart#1590]
I want to reproduce the following chart using the library. 

<img width="446" alt="image" src="https://github.com/imaNNeo/fl_chart/assets/39571970/ea0380e4-ba05-41e7-90ee-4b56fa6066d0">

This chart shows the number of active credits and total amount borrowed (of the active credits) in the same chart. As you can see, each group has different magnitudes, so it is not as straightforward as to just add another LineChartBarData element to the chart. In the left are the amount borrowed stops, and in the right side are the active credit stops.

Is there any way to achieve this? 

Am I missing any details available in the library? Is it a missing but achievable feature or is something out scope?

**Comment by imaNNeo** [comment]
You can stack two lines with de-active and active colors on top of each other.
Take a look at the below sample (source code is [here](https://gist.github.com/imaNNeo/4a297183566e8b556e3244e6e1d41e52)):

https://gist.github.com/assets/7009300/5f8b68de-6e1b-4c9c-b28e-b29b91100565
