### ISSUE TITLE
Discrepancy in documentation

### ISSUE THREAD

**Issue by tirendus** [imaNNeo/fl_chart#1608]
BarChartData documentation states that default alignment is BarChartAlignment.spaceBetween
https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/bar_chart.md#barchartdata

in src/chart/bar_chart/bar_chart_data.dart
the BarChartData is initialized with spaceEvenly
`alignment = alignment ?? BarChartAlignment.spaceEvenly,`

**Comment by imaNNeo** [comment]
You're right. We need to update the documentation in [bar_chart.md](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/bar_chart.md#barchartdata).
