### ISSUE TITLE
How can I set the bottom title with the date and interval by time?

### ISSUE THREAD

**Issue by gogommd** [imaNNeo/fl_chart#1616]
Since my data have the date and time value, I want to set the bottom title with the date and interval by time to display the value(bloodSugar).
```dart
class BloodSugarModel (
  final String? bsID;
  final double bloodSugar;
  final String? remark;
  final String date;
  final String time;
)
```
Wanted the chart
<img width="336" alt="image" src="https://github.com/imaNNeo/fl_chart/assets/83054868/94d2e440-e0bf-4b84-8eb2-a3cadbc578e3">

**Comment by e4ky** [comment]
给你提供一个思路，再多设置一个double的时间属性，把日期转换成时间戳，然后x轴的对你的数据时间戳进行绘制Line，并对X轴的数据标签进行格式转化输出，即把时间戳转换成"MM/dd/yyyy"的文字标签内容。

**Comment by imaNNeo** [comment]
> 给你提供一个思路，再多设置一个double的时间属性，把日期转换成时间戳，然后x轴的对你的数据时间戳进行绘制Line，并对X轴的数据标签进行格式转化输出，即把时间戳转换成"MM/dd/yyyy"的文字标签内容。

Please speak English
