### ISSUE TITLE
Best way to synchronize and show tool tips of an X value across multiple charts

### ISSUE THREAD

**Issue by lamarios** [imaNNeo/fl_chart#1641]
Hi, 
Thanks for the great library !

I was wondering if you have a suggestion on what is the best way to synchronize and programmatically touch the same X value across multiple charts,

I'm able to do it  but the performance degrades quickly the more graphs  and lines there are on slower hardware (especially web).

Here's a video of what i already implemented:
[Screencast from 2024-04-26 16-20-59.webm](https://github.com/imaNNeo/fl_chart/assets/1192563/519a8aa2-0c1a-4a06-9320-46c544156915)

You can see that there is already some delay in the video and I have a fairly recent machine.

Currently what I do is I have a Cubit (using bloc library)  that holds the X value that is being hovered and  a builder around each graph that rebuilds when that X value changes. I programmatically select all the touched spots and display the tooltips and draw the vertical line on each graph.

I believe the issue is that all the graphs are rebuilt every time the X date changes, I implemented a throttle and debounce so that it doesn't rebuild for each pixel the mouse moves but it is still slow on some lower end machines. 

Do you know if there is a better approach of handling this ?

**Comment by lamarios** [comment]
I managed to solve it if anyone is interested but it's a pretty hacky way:

I built my own tool tip layer on top of the graph. So each graph is now in a stack with a transparent container on top that handle the touch events and will draw it's own tool tips which mean that when the highlighted date changes the graph doesn't actually rebuid and only the top layer does.

Video: 
[Screencast from 2024-04-29 13-28-52.webm](https://github.com/imaNNeo/fl_chart/assets/1192563/7ce25a16-8a8a-464b-b1f0-0ad90eba6648)

**Comment by najeebkp** [comment]
Hi @lamarios 
I'm also looking for a solution to synchronise multiple line charts.Im new to flutter by the way. Do you have any code example on how you implemented this functionality for syncing multiple graphs? It would be helpful for me and many others if you can share it here.

**Comment by lamarios** [comment]
Unfortunately I can't share the code as it is work stuff.

But the implementation is fairly easy, let  me write down a hierarchy of widgets



```
MyGraphWidget(graphData, highlightedXValue)
   |_ Stack
           |_ FlLineChart(graphData, disableTooltips:true)
           |_ Positioned(left: width of Y axis caption, bottom: height of X axis caption)
                   |_ ToolTipLayer(graphData, highlightedXValue) # custom widget where we draw the tooltips and handle touch events
                            |_ LayoutBuilder # So we know how wide is our tooltip layer
                                         |_ # Below here, you can draw your vertical line and tooltips because you have all the data you need
                                             #  width of  tooltip layer, range of your graph (min date and max date)
                                             #  so you can calculate which date is highlighted then from the graphData find which point is the nearest
                                             # and build your own tooltip at the location of the highlighted date
```

**Comment by najeebkp** [comment]
Sure, Thanks for the hierarchy. 🙏
