### ISSUE TITLE
Add gradient to bar chart and pie chart

### ISSUE THREAD

**Issue by MobileMon** [imaNNeo/fl_chart#166]
Instead of a solid color, can I use a gradient to fill in the pie chart segments and bar chart segments?

**Comment by krupeshxebia** [comment]
Yes, I want to add gradient in bar graph rods. please add this feature.

**Comment by imaNNeoFighT** [comment]
What kind of gradient do you need in the PieChart?
@MobileMon

**Comment by bdairy** [comment]
to use gradient colors like this 
![image](https://user-images.githubusercontent.com/10797121/83578007-545a9780-a53e-11ea-8868-1d44f7b02128.png)

**Comment by imaNNeoFighT** [comment]
It has just been added in [0.12.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.12.0) version.

Check it [this sample](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#sample-3-source-code)
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_3.png" width="300" >

The pie chart gradient is yet to come!

**Comment by Nirsu** [comment]
Hello guys,
I didn't want to open a new issue, since this one was still open.
I would like to know if there was any information about the gradient for pie charts, because I would like to make a gradient like that:
![image](https://user-images.githubusercontent.com/33753020/133591413-88d0f889-b6e1-4307-9673-baf4679e36cd.png)

**Comment by asaboor-art** [comment]
![Screenshot 2022-08-19 234656](https://user-images.githubusercontent.com/89475152/185686966-e729c91b-b681-43f4-a000-a7297808ed91.png)
i want this type of gradient color design in Doughnut Chart.. can someone help me?

**Comment by asaboor-art** [comment]
<script>
            const settings = {
            canvasId   : 'canvas',  
            fillAmount : 85,        
            baseAmount : 100,       
            fillColor  : '#64c832', 
            baseColor  : '#EBF5FB', 
            lineWidth  : 20,     
          }
          const state = {
            curAmount: 0,
            curDegrees: 0
          }
          const canvas = document.getElementById(settings.canvasId)
          canvas.halfWidth = canvas.width / 2
          canvas.halfHeight = canvas.height / 2
          const ctx = canvas.getContext('2d')
          animate()
          function animate () {
            update()
            draw()
            if (state.curAmount < settings.fillAmount) {
              requestAnimationFrame(animate)
            }
          }
          function update () {
            state.curAmount += 1
            state.curDegrees = (state.curAmount / settings.baseAmount) * 360
          }
          function draw () {
            ctx.clearRect(0, 0, canvas.width, canvas.height)
            drawArc(0, 360, settings.baseColor)
            drawArc(-90, (state.curDegrees - 90), settings.fillColor)
            drawText(state.curAmount)
          }
          function drawArc (startDegrees, endDegrees, lineColor) { 
            ctx.lineWidth = settings.lineWidth
            ctx.strokeStyle = lineColor
            ctx.beginPath()
            ctx.arc(
              canvas.halfWidth,
              canvas.halfHeight,
              canvas.halfWidth - (settings.lineWidth / 2),
              degreesToRadians(startDegrees),
              degreesToRadians(endDegrees)
            )
            ctx.stroke()
          }
          function drawText (text) {
            ctx.fillStyle = settings.fillColor
            ctx.font = 'bold ' + settings.fontSize + ' ' + settings.fontFace
            ctx.textAlign = 'center'
            ctx.fillText(
              text,
              canvas.halfWidth,
              canvas.halfHeight + (parseInt(settings.fontSize) / 3)
            )
          }
          function degreesToRadians (degrees) {
          return degrees * Math.PI / 180
          }
          document.getElementById('replay').addEventListener('click', function() {
            state.curAmount = 0
            state.curDegrees = 0
            animate()
          })
    </script>
    
    <div id="canvas-wrap">
                <canvas id="canvas" width="300" height="300"></canvas>
                <div class="donut-result">
                   <p><span>9,8969</span> Estimated Overtime Owed</p>
                 </div>
              </div>
              
              #canvas-wrap {display: flex;justify-content: center;align-items: center;width: 100%;height: 100%;}

**Comment by raldhafiri** [comment]
I have created pull request 
https://github.com/imaNNeo/fl_chart/pull/1511

it will add support for piechart gradients

**Comment by imaNNeo** [comment]
PieChart gradient is added in [0.66.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.66.0). 
Thanks, @raldhafiri  for contributing 🚀

**Comment by imaNNeo** [comment]
> It has just been added in [0.12.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.12.0) version.
> 
> Check out [this sample](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/bar_chart.md#sample-3-source-code) <img alt="" width="300" src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/bar_chart/bar_chart_sample_3.png">
> 
> The pie chart gradient is yet to come!

I think now we're done with this issue ;)
