### ISSUE TITLE
Please, add gradient colours for the line depending on Y value for the LineChart (for example if y > 10 I need to set one color for the line, if y > 100 it should be another color)

### ISSUE THREAD

**Issue by MishaPadalka** [imaNNeo/fl_chart#1695]
<img width="423" alt="image" src="https://github.com/imaNNeo/fl_chart/assets/58531288/5568523f-d444-4545-9efb-18a598f8ecab">

I mean to have something like that, when the color of the line depends on the y value of the spot

**Comment by Tobbyte** [comment]
not sure what you mean. Could adding Stops to your gradient solve your problem? You could use them to define hard edges. https://css-tricks.com/books/greatest-css-tricks/hard-stop-gradients/

**Comment by imaNNeo** [comment]
Yes, you can add stops to your gradient to achieve the result.
Check the [LinearGradient](https://api.flutter.dev/flutter/painting/LinearGradient-class.html) and stops property. You can use it in the `gradient` property of [LineChartBarData](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/line_chart.md#linechartbardata)
