### ISSUE TITLE
Add or subtract from minX, miny, maxX and maxY

### ISSUE THREAD

**Issue by JohanScheepers** [imaNNeo/fl_chart#1701]
The ability to add or subtract a value from auto calculated minX, miny, maxX and maxY

**Is your feature request relasted to a problem? Please describe.**
The max or min sits on the edge of the chart, ill look better if their are some 'padding' in the chart

**Describe the solution you'd like**
```
LineChartData(maxX: maxX + 2,
                      minX: minX - 2,
                      maxY: maxY + 2,
                      minY: minY - 2,
```

**Additional context**
![image](https://github.com/imaNNeo/fl_chart/assets/30056110/6f20fee3-a5cc-4649-bfc0-e9b3ca985010)

**Comment by imaNNeo** [comment]
I think it will be cleaner if you add it manually in my opinion. 
Because it is a rare use-case, so it doesn't make sense to have it inside the chart features.
