### ISSUE TITLE
Dithering bug

### ISSUE THREAD

**Issue by Artein** [imaNNeo/fl_chart#1702]
**Don't create a duplicate issue.**
No similar open issue was found.

**Describe the bug**
LinearChart and PieChart (probably other charts as well) constantly change the size by a few pixels, creating a dithering appearance.

**To Reproduce**
Use values with very long fractional parts (high precision), such as `0.124325346342756236`.
Edit: Well, seems like the issue is not in that. My LinearChart uses small integers (DateTime.weekday as X, and [0; 12] as Y).
Edit 2: Lowering precision in PieChart values also didn't help.

**Screenshots**
https://github.com/imaNNeo/fl_chart/assets/1109722/8e0899d0-ca0c-4ef5-b59b-9536ddd67e75
The effect can be seen in the center of PieChart (kinda a starting line from which bottom part shifts down and up a bit), and on horizontal values of LiniearChart (especially on values between Thu and Sun)

**Versions**
 Flutter: 3.19.6
 FlChart: 0.68.0

**Comment by Artein** [comment]
I am suggesting to clamp incoming values to precision required to build charts. Currently, I have implemented following workaround as extension to my double values:
```
double fractionPrecision(int n) {
    // Split the value into integer and fractional parts
    int integerPart = truncate();
    double fractionalPart = this - integerPart;

    // Adjust the fractional part to the desired precision
    double mod = pow(10.0, n) as double;
    double adjustedFractionalPart = (fractionalPart * mod).round().toDouble() / mod;

    // Merge the integer and adjusted fractional parts
    return integerPart + adjustedFractionalPart;
  }
```

**Comment by techouse** [comment]
> Screenshots
> https://github.com/imaNNeo/fl_chart/assets/1109722/8e0899d0-ca0c-4ef5-b59b-9536ddd67e75

From the screenshot I see that you use Impeller. Can you try with Skia?

**Comment by Artein** [comment]
> > Screenshots
> > https://github.com/imaNNeo/fl_chart/assets/1109722/8e0899d0-ca0c-4ef5-b59b-9536ddd67e75
> 
> From the screenshot I see that you use Impeller [because of the line chart rendering issue](https://github.com/imaNNeo/fl_chart/issues/1625). Can you try with Skia?

Yes, it fixes the issue. 
Unfortunately, having shaders lazy compilation across the whole app is even worse.

Is there any workaround for the Impeller?

**Comment by techouse** [comment]
> Is there any workaround for the Impeller?

https://github.com/imaNNeo/fl_chart/issues/1625#issuecomment-2165505325

**Comment by imaNNeo** [comment]
Let's follow it on #1625
