### ISSUE TITLE
Scatter plot with different marker ?

### ISSUE THREAD

**Issue by sczesla** [imaNNeo/fl_chart#1706]
As far as I can see, only circle markers are possible in scatter plots.

Different markers may be useful to distinguish individual quantities. 

My actual idea was to build a heat map out of "square pixels" using a scatter plot, which could also take advantage of the tooltip to show quantitative information. Is there already way to do this?

**Comment by imaNNeo** [comment]
You can customize your marker by the `dotPainter` property,
Please take a look at the [Scatter Sample 2](https://github.com/imaNNeo/fl_chart/blob/main/example/lib/presentation/samples/scatter/scatter_chart_sample2.dart)

Uploading CleanShot 2024-07-19 at 23.47.14.mp4…
