### ISSUE TITLE
displaying LineTooltipItem when clicking on SideTitleWidget

### ISSUE THREAD

**Issue by HarchenkoArtyom** [imaNNeo/fl_chart#1707]
Hello everyone, can you tell me how to implement the display of LineTooltipItem by clicking on the SideTitleWidget, as it works now when pointing at points on the chart. That is, click on the SideTitleWidget element and display all the corresponding values ​​on the graph.

**Comment by HarchenkoArtyom** [comment]
@imaNNeo can you please help with this?

**Comment by imaNNeo** [comment]
You can implement it by adding tap functionality on the side titles (using Inkwell, or GestureDetector widgets)
Then you can use `showingIndicators` property to show them. You can also check [sample5](https://github.com/imaNNeo/fl_chart/blob/main/example/lib/presentation/samples/line/line_chart_sample5.dart):

https://github.com/user-attachments/assets/5cf29c94-b5fa-46bc-82db-461c62fae102

**Comment by HarchenkoArtyom** [comment]
@imaNNeo how to call showingIndicators in the sidebar?
