### ISSUE TITLE
Hacky solution for zooming and displaying extra data / titles across the chart

### ISSUE THREAD

**Issue by Tobbyte** [imaNNeo/fl_chart#1712]
Hi everyone,

I wanted to share my hacky workaround for making the chart zoomable and placing the (bottom) titles above the chart to be able to show whatever additional data.

It's not the most elegant solution, but maybe it can help someone else out there.
bases on older solutions of @theovogel  [here](https://github.com/imaNNeo/fl_chart/issues/71#issuecomment-1414267612) and @techhouse [here](https://github.com/imaNNeo/fl_chart/issues/776#issuecomment-1212109108)

minimal demo: [repo](https://github.com/Tobbyte/chartdemo/blob/main/lib/main.dart)
<img width="346" alt="Bildschirmfoto 2024-07-17 um 09 44 59" src="https://github.com/user-attachments/assets/74a25e31-f29d-4802-82bb-9c753db946db">

I use this to display week ticks across the chart, like so.
<img width="397" alt="Bildschirmfoto 2024-07-17 um 09 47 14" src="https://github.com/user-attachments/assets/5f037507-61f9-4d3a-98b6-120de1874103">

cheers :vulcan_salute:

**Comment by imaNNeo** [comment]
Can you please just write your idea in thread #71 and close this issue?
Because it doesn't make sense to have a new issue for that. It is completely related to #71

**Comment by Tobbyte** [comment]
https://github.com/imaNNeo/fl_chart/issues/71#issuecomment-2240945146

**Comment by imaNNeo** [comment]
> [#71 (comment)](https://github.com/imaNNeo/fl_chart/issues/71#issuecomment-2240945146)

Thanks a lot!
