### ISSUE TITLE
BarChart Side Title Widget

### ISSUE THREAD

**Issue by ivanchaukn** [imaNNeo/fl_chart#1714]
When we rotate the titles and if the title is long, it gets hidden under the bar. How can I shift or change the alignment of title so that the full title is visible? 

fl_chart: ^0.68.0

![Simulator Screenshot - iPhone 15 - 2024-07-18 at 23 20 49](https://github.com/user-attachments/assets/8812653b-721d-4b5c-86e8-aceccefff7e1)

**Comment by imaNNeo** [comment]
There's a `reservedSize` in the [SideTitles](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/base_chart.md#sidetitles) that you can use to increase the space for texts.

**Comment by ivanchaukn** [comment]
![Screenshot 2024-08-26 at 9 37 43 PM](https://github.com/user-attachments/assets/a9e854d8-694d-4fab-8397-6c783b663707)

How can I make the text left aligned? I tried setting the textAlign property in the Text widget but that doesn't work
