### ISSUE TITLE
Custom Interval Spacing on Axis for LineCharts

### ISSUE THREAD

**Issue by saavy1** [imaNNeo/fl_chart#1747]
**Describe the solution you'd like**
Not sure what an ideal API would be for this, but the attached image shows an example

**Describe alternatives you've considered**
I think the alternative is simply having even spaced ticks
 
**Additional context**
Desired graph
![image](https://github.com/user-attachments/assets/4c3f2bc6-d5c1-472c-a606-47c350a71295)

Current graph
![image](https://github.com/user-attachments/assets/e7cc8037-d8fb-4e7b-922c-a8c58ba87865)

**Comment by saavy1** [comment]
Sorry if this is a duplicate, I searched and couldn't find anything related to this, TIA

**Comment by saavy1** [comment]
Closing my own request as it's another request for a logarithmic axis

**Comment by imaNNeo** [comment]
Yes it is here: #434
