### ISSUE TITLE
[CI] Code Verification not running tests

### ISSUE THREAD

**Issue by Peetee06** [imaNNeo/fl_chart#1791]
**Describe the bug**
The GitHub Actions verification workflow calls `make test` which is a non-existing target. Therefore no tests are run. The correct target is `runTests`.

**To Reproduce**
See step `Run tests` [here](https://github.com/imaNNeo/fl_chart/actions/runs/12038213937/job/33563379499)

**Screenshots**
<img width="348" alt="Screenshot 2024-11-27 at 05 41 32" src="https://github.com/user-attachments/assets/990266ea-806e-44c9-90ed-76aa0c7040ed">

**Comment by imaNNeo** [comment]
Oh man, 
Thanks for finding and fixing it!

**Comment by Peetee06** [comment]
Closing because fixed in #1792
