### ISSUE TITLE
Feature Request: Trend Lines

### ISSUE THREAD

**Issue by farzadpanahi** [imaNNeo/fl_chart#293]
Do you consider adding the trend line feature to this lib in the future? My goal is to produce trend lines as we see them on graphs like Google Fit's weight graph:

![google-weight-trend-line](https://user-images.githubusercontent.com/3793563/78731505-c6bf4a80-78f4-11ea-931c-57c1d1d28288.png)
_Dark blue is trend line and light blue is the actual data-points._

Looks like there is a similar implementation in Google Charts lib:
https://developers.google.com/chart/interactive/docs/gallery/trendlines

That would be a good feature to have. For now, I am going to try to calculate the trend line datapoints myself and try to use the curve feature of your lib to see if it can be done this way. But I guess the curve would look better if it was calculated in the lib :)

**Comment by FMorschel** [comment]
Hi! I'm no mathematician, and to my understanding, there are some differences in how to calculate this when we have different graphs like log/expo, but I have asked some AIs how to calculate linear trendlines and this is what I've got:

```dart
class SpotsTrendline extends DelegatingList<FlSpot> {
  SpotsTrendline(List<FlSpot> spots)
      : assert(spots.length >= 2),
        super(trendline(spots));

  static List<FlSpot> trendline(List<FlSpot> spots) {
    final mySpots = [...spots.map(MySpot.new)];
    mySpots.sort();
    final xValues = [...mySpots.map((e) => e.x)];
    final yValues = [...mySpots.map((e) => e.y)];
    final xMed = xValues.reduce((a, b) => a + b) / xValues.length;
    final yMed = yValues.reduce((a, b) => a + b) / yValues.length;
    final xSomaQuadDifMedia =
        xValues.reduce((value, element) => pow(element - xMed, 2) + value);
    final somaProdDifMedia = mySpots
        .map((e) => (e.x - xMed) * (e.y - yMed))
        .reduce((value, element) => value + element);
    final m = somaProdDifMedia / xSomaQuadDifMedia;
    final b = yMed - m * xMed;
    return [
      FlSpot(xValues.first, m * xValues.first + b),
      FlSpot(xValues.last, m * xValues.last + b),
    ];
  }
}

class MySpot extends FlSpot implements Comparable<MySpot> {
  MySpot(FlSpot spot) : super(spot.x, spot.y);

  @override
  int compareTo(MySpot other) {
    final xResult = x.compareTo(other.x);
    if (xResult != 0) return xResult;
    return y.compareTo(other.y);
  }
}
```

I only added a new `LineChartBarData` like the following:

```dart
const spots = [
  FlSpot(0, 3),
  FlSpot(2.6, 2),
  FlSpot(4.9, 5),
  FlSpot(6.8, 3.1),
  FlSpot(8, 4),
  FlSpot(9.5, 3),
  FlSpot(11, 4),
];
final data = LineChartBarData(
  spots: spots,
  isCurved: true,
  curveSmoothness: 0.18,
  color: Colors.amber,
  barWidth: 5,
  isStrokeCapRound: true,
  dotData: const FlDotData(
    show: true,
  ),
  belowBarData: BarAreaData(
    show: true,
    color: Colors.transparent,
  ),
);
final trendline = LineChartBarData(
  spots: SpotsTrendline(spots),
  isCurved: true,
  curveSmoothness: 0.18,
  color: Colors.cyan,
  barWidth: 5,
  isStrokeCapRound: true,
  dotData: const FlDotData(
    show: true,
  ),
  belowBarData: BarAreaData(
    show: true,
    color: Colors.transparent,
  ),
);
```


![image](https://github.com/imaNNeo/fl_chart/assets/52160996/a1566a80-ac67-49f7-8dc7-092752b0ab96)

**Comment by imaNNeo** [comment]
> differences in how to calculate this when we have different graphs like log/expo, but I have asked some AIs how to calculate linear trendlines and this is what I've got:

Thanks for your research.
Btw, I think it can be done by the developer with any algorithm that they use. So I will close this issue as we don't need to touch the internal fl_chart codes
