### ISSUE TITLE
I need BarChart & Linechart's extraLinesData

### ISSUE THREAD

**Issue by jpoh281** [imaNNeo/fl_chart#476]
![image](https://user-images.githubusercontent.com/54665433/96693462-3c3ac600-13c2-11eb-9205-4a59210d7cba.png)
 +
![image](https://user-images.githubusercontent.com/54665433/96693521-4eb4ff80-13c2-11eb-8c94-83d0b10d5083.png)

and I use barchart in SingleChildScrollview.
How can I adjust width interver ?

**Comment by imaNNeoFighT** [comment]
Sorry I didn't understand!

**Comment by jpoh281** [comment]
I understand this package, bar chart can't extraLines. 
but I want draw extraLine

**Comment by imaNNeoFighT** [comment]
Aha got it.

**Comment by matbujnowicz** [comment]
<img width="677" alt="Screenshot 2020-11-10 at 15 18 04" src="https://user-images.githubusercontent.com/32484389/98693249-f55c4280-2367-11eb-9755-67504a400770.png">
I think I have the same problem. We need a dashed horizontal line to show the average. 

If you are planning to add this feature, may I ask in how long I could expect it? As I need to know whether I should think of some Stack workaround or I should just wait a bit.

Thanks for the great work anyway!

**Comment by imaNNeoFighT** [comment]
I understand you need it. But keep in mind that I have my personal life and I have to spend time on my personal stuff. I have a little time for maintaining this repo or something like that.
Donation motivates me to work more here (as you know everyone needs to make money somehow).
Also, I suggest you make your hands dirty and read the source code. Then you can make your merge request.
Thanks, regards!

**Comment by DooRooSA** [comment]
I've started looking at the code to add this feature, tackling this as my first-ever contribution to OSS. The ExtraLinesData class is defined in line_chart_data.dart . We can reuse this class for the BarChart as well. Just want to find out whether I leave the class in that file, because my gut feel is that it should move to a more generic file. I'm just not sure where to move it to

**Comment by imaNNeoFighT** [comment]
> I've started looking at the code to add this feature, tackling this as my first-ever contribution to OSS. The ExtraLinesData class is defined in line_chart_data.dart . We can reuse this class for the BarChart as well. Just want to find out whether I leave the class in that file, because my gut feel is that it should move to a more generic file. I'm just not sure where to move it to

Hi @DooRooSA. 
Sorry for my late answer.
I'm very happy that you are trying to do your first-ever contribution.
It seems someone else created a PR for this. But it doesn't mean that you cannot implement it in your way.
I will merge a branch that will be ready faster. Or maybe you can try on another issue.

**Comment by DooRooSA** [comment]
hi @imaNNeoFighT,

No worries, if it's been done already, it'll be better if I carry on with something else. Have a great day!

**Comment by imaNNeoFighT** [comment]
Have a great day!

**Comment by FriendlyNeighbor** [comment]
was this successfully merged?

**Comment by JoshMart** [comment]
It appears as if this has not been resolved yet. It would be very useful for me as well to draw mean and standard deviation horizontally on a bar chart.

**Comment by imaNNeoFighT** [comment]
No. The PR contributor was not responsive and I just closed the PR.
Now everyone can take this task and implement it.

**Comment by JoshMart** [comment]
Thanks for the update. I am working on enabling this feature and using code from previous PRs as a starting point.

**Comment by imaNNeo** [comment]
This feature is added in [0.60.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.60.0). Check it out!
