### ISSUE TITLE
How to implement LineChartData.touchCallback?

### ISSUE THREAD

**Issue by ristiisa** [imaNNeo/fl_chart#484]
When I quickly tap on a graph the touchCallback is called twice with touchInput being FlPanStart and FlPanEnd. But FlPanEnd has always X values as 0 and sometimes FlPanStart has no lineBarSpots at all.

**Versions**
Flutter: 1.22.2
FlChart: 0.12.0

**Comment by imaNNeo** [comment]
It would be fixed in our latest release `0.60.0`.
BTW sorry for my late answer. 
Feel free to re-open it if you found it buggy again.
