### ISSUE TITLE
Popup/tooltip doesn't show up when x values are close

### ISSUE THREAD

**Issue by masc-it** [imaNNeo/fl_chart#489]
Hello @imaNNeoFighT, first of all, great job with this lib! 

I've successfully implemented the line chart, but I am experiencing the issue shown in the pic below.

![Screenshot_16041647041](https://user-images.githubusercontent.com/40116397/97785669-d0691200-1ba6-11eb-8771-6d10808d93e3.png)

On the x-axis I got dates, which can be really close to each other (in this scenario the last 2 points have a delta of 15 mins) and whose corresponding y-values might be really different.

When I tap/slide on the chart, the tooltip/popup associated with the last, lower point, doesn't show up, but it does with the one right above it.

If it can be of any help:

<pre>
<code>
..
bottomTitles: SideTitles(
          showTitles: true,
         
          getTextStyles: (value) => const TextStyle(
              color: Color(0xff68737d),
              fontSize: 14),
          getTitles: (value) {
            final DateTime date =
                DateTime.fromMillisecondsSinceEpoch(value.toInt());
            final parts = date.toIso8601String().split("T");
            return parts.first + "\n" + parts[1].split(".")[0];
          },
          margin: 12,
          interval:
              (widget.spots[widget.spots.length - 1].x - widget.spots[0].x), 
        ),
..
</pre>
</code>

Any idea about I can possibly fix this? :/

**Comment by imaNNeoFighT** [comment]
Hi, did you check `fitInsideHorizontally` in [LineTouchTooltipData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#LineTouchTooltipData)?

**Comment by masc-it** [comment]
> Hi, did you check `fitInsideHorizontally` in [LineTouchTooltipData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/line_chart.md#LineTouchTooltipData)?

it's not about a graphical problem.

The touch event on that spot (the lower one), just doesn't make the tooltip to show up. It always triggers the above tooltip. (same situation if I switch the y-values)

**Comment by imaNNeoFighT** [comment]
Can you provide ma a reproducible code (a `main.dart` file)
