### ISSUE TITLE
Remove repo_files/documentations

### ISSUE THREAD

**Issue by mhmdanas** [imaNNeo/fl_chart#495]
I believe that we should remove `repo_files/documentations`. Here are my reasons:
- It mostly contains the same information as the doc comments (`///`).
- If something changes and doc comments are changed, one has to remember to change it in `repo_files/documentations` too. And if it mistakenly goes out of sync, we will be showing outdated information to devs, which might cause bugs. This adds to the maintenance burden.
- One can link to [the API reference](https://pub.dev/documentation/fl_chart/latest/) instead, which has a better interface in addition to many other useful features like searching. One thing to note here is that the latest version of the API reference will not show the docs of `dev`, but of the latest version published on pub. However, I think that's only a minor concern.

**Comment by imaNNeo** [comment]
Hi. First of all, I am sorry about my late response.
Its more than two years though :)

BTW I remember I read your comment when you posted it, but I forgot to answer.
About your first point yes you are right, we are going to make some changes to have a documentation website and cover more details and explanations.
I think API reference docs and what we write have some differences. API references docs are short and concise but the documentation that we write contains a lot of details, examples, maybe videos, gifs, or interactive charts using [zapp](https://zapp.run).
