### ISSUE TITLE
Pie chart show value on Click

### ISSUE THREAD

**Issue by waqaryounusjatt788** [imaNNeo/fl_chart#496]
I have set custom Text in Center Space of Pie Chart  when i am pressing long click then value is showing but i want this thing on click event please see below sample.
![sd](https://user-images.githubusercontent.com/65191117/98942169-70ac2880-250f-11eb-81d7-87c06a1e034c.gif)

**Comment by animalnots** [comment]
@waqaryounusjatt788 ,
You can do that by commenting out the default code and adding custom handler logic.
` PieChartData(
                                pieTouchData: PieTouchData(
                                    touchCallback: (pieTouchResponse) {
                                  setState(() {
                                    touchedIndex =
                                        pieTouchResponse.touchedSectionIndex ??
                                            touchedIndex;

                                    // if (pieTouchResponse.touchInput
                                    //         is FlLongPressEnd ||
                                    //     pieTouchResponse.touchInput is FlPanEnd) {
                                    //   touchedIndex = -1;
                                    // } else {
                                    //   touchedIndex =
                                    //       pieTouchResponse.touchedSectionIndex;
                                    // }
                                  });
                                }),
                                borderData: FlBorderData(
                                  show: false,
                                ),
                                sectionsSpace: 3,
                                centerSpaceRadius: 60,
                                sections: showingSections()),
                          ),`

**Comment by imaNNeo** [comment]
Check it out [here](https://zapp.run/edit/flutter-z31206kr3130?entry=lib/main.dart&file=lib/main.dart):

https://user-images.githubusercontent.com/7009300/215541027-fba80b92-184d-434d-9261-9ee11eb750ad.mov
