### ISSUE TITLE
Is there a way to insert a slider or manage the tap from outside the graph?

### ISSUE THREAD

**Issue by antonioconeseKP** [imaNNeo/fl_chart#585]
Something like this:
![slider](https://user-images.githubusercontent.com/79635157/109135366-46e1df00-7757-11eb-9325-5e7be2dde3b9.PNG)

Or is there a way to make the LineTouchData always visible (even before tapping on the graph)?
Thank's for your work.

**Comment by imaNNeoFighT** [comment]
You can make it visible without touching it.
Check LineChartSample 5 ([Source Code](/example/lib/line_chart/samples/line_chart_sample5.dart))
<img src="https://github.com/imaNNeoFighT/fl_chart/raw/master/repo_files/images/line_chart/line_chart_sample_5.png" width="300" >
