### ISSUE TITLE
Set one SpotLine in graph dynamically

### ISSUE THREAD

**Issue by LukeKLM** [imaNNeo/fl_chart#595]
Hello,

is there any way how to create **SpotLine** in **LineChart** dynamically?

I know you can create SpotLines in **belowBarData** attribute and you have there checking function **checkToShowSpotLine**.

But in this function is only a FlSpot and i can't decide when to show it. I need to compare it with touched spot. In documentary is a constant value for cheking if return true or false.

Thank you for help.

**Comment by imaNNeoFighT** [comment]
I didn't understand your demand.
Can you explain a little more?
Do you need anything else other than `FlSpot` in `checkToShowSpotLine`?
We can send the index of that FlSpot. does it help you to decide?
