### ISSUE TITLE
The getter 'touchedSectionIndex' isn't defined for the type 'PieChartSectionData'

### ISSUE THREAD

**Issue by SandyUndefined** [imaNNeo/fl_chart#629]
Hey, I m facing this error
` The getter 'touchedSectionIndex' isn't defined for the type 'PieChartSectionData'.
Try importing the library that defines 'touchedSectionIndex', correcting the name to the name of an existing getter, or defining a getter or field named 'touchedSectionIndex'.`

**To Reproduce**
I have used your example files.
pie_chart_sample1.dart
pie_chart_sample2.dart

**Screenshots**
![2021-04-06](https://user-images.githubusercontent.com/31213192/113704334-a093dc80-96f9-11eb-86af-ba483d14f9ba.png)

**Versions**
*Flutter --version*
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (2 months ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.

*FlChart*
fl_chart: ^0.35.0

**Comment by imaNNeoFighT** [comment]
Please check it with Flutter version 2.0 (stable channel)
BTW touchedSection is nullable, and I think you should access it with hard null check (like `pieTouchResponse.touchedSection!.touchedSectionIndex`).

**Comment by SandyUndefined** [comment]
Hey @imaNNeoFighT 
Just updated flutter 
*flutter --version*
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (6 days ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2

![error2](https://user-images.githubusercontent.com/31213192/113851514-3478ad80-97b9-11eb-9eb0-755211e7b24a.PNG)

Still showing this error

**Comment by thirdsalinga** [comment]
Hi, idk if I fixed it by removing 'touchSection'.
touchedIndex =  pieTouchResponse.touchedSectionIndex;

**Comment by SandyUndefined** [comment]
@thirdsalinga It doesn't fix it but somehow it's better than nothing.

**Comment by thirdsalinga** [comment]
It solved the problem in my case, hope you find the solution 🙏🏽

**Comment by imaNNeoFighT** [comment]
How did you solve it?

**Comment by imaNNeoFighT** [comment]
Can you verify that the problem exists in fl_chart?

**Comment by Sully55** [comment]
i have the same issue The argument type 'void Function(FlTouchEvent)' can't be assigned to the parameter type 'void Function(FlTouchEvent, PieTouchResponse?)?', did anyone solve it?
