### ISSUE TITLE
Stacked Pie (Donut) Chart

### ISSUE THREAD

**Issue by VVErmac** [imaNNeo/fl_chart#630]
Hello, is it possible to make such kind of chart?
As here in example:
![download](https://user-images.githubusercontent.com/32908961/113709632-05900800-96e3-11eb-9e9b-f5acb6f74c5c.png)

I have tried to make two charts as StackedWidget, but it doesn't look cool from code perspective.

**Comment by imaNNeo** [comment]
Oh, this issue is a duplicate. Please follow the older one: #480
