### ISSUE TITLE
Distorted plotting of graph and show left title 0 for values with no data

### ISSUE THREAD

**Issue by vaibhiarora03** [imaNNeo/fl_chart#762]
I am facing 2 issues:-

1. I am getting a distorted graph created upon receiving the data. The graph gets distorted when negative values are plotted. Attaching the screenshots below...

screenshot_1:-
![WhatsApp Image 2021-08-30 at 4 43 25 PM](https://user-images.githubusercontent.com/54858042/131968681-369c03ea-d003-41ba-a24e-6d43a947b181.jpeg)

screenshot_2:-
![WhatsApp Image 2021-08-30 at 4 43 26 PM](https://user-images.githubusercontent.com/54858042/131968700-23277331-183f-442d-aa3d-ceed57304d5a.jpeg)

screenshot_3:-
![WhatsApp Image 2021-09-02 at 7 46 58 PM](https://user-images.githubusercontent.com/54858042/131968722-e9c018f9-c4b1-4f89-aa80-e265f2d2124d.jpeg)

screenshot_4:-
![WhatsApp Image 2021-09-02 at 7 48 21 PM](https://user-images.githubusercontent.com/54858042/131968748-b6dccbe4-8b82-49a7-9f1a-41ffb0cfbbdd.jpeg)

**Issue 2:-**

2. If we have a set of data that's 0, how do I show 0 as a value on the left side. All other values are being shown correctly but unable to show 0 as a value. Attaching both screenshots of with and without values. 

Data with values "0":-
![WhatsApp Image 2021-09-03 at 12 58 53 PM](https://user-images.githubusercontent.com/54858042/131967744-9661a244-afba-4e3b-9f2f-a4458c3a0162.jpeg)

Data with different values:-
![WhatsApp Image 2021-09-03 at 1 04 48 PM](https://user-images.githubusercontent.com/54858042/131968291-14c9d522-0a56-4c06-b916-f5b460973e04.jpeg)

Thanks

**Comment by imaNNeo** [comment]
Guys the issue is not descriptive and the images are too large. Can you please share me a reproducible code (a simple main.dart file)?
