### ISSUE TITLE
fl_chart and InteractiveViewer doesn't allow pan gestures.

### ISSUE THREAD

**Issue by Piero512** [imaNNeo/fl_chart#790]
**Describe the bug**
When using InteractiveViewer to create a pan-able, zoom-able chart in mobile, the default gesture recognizers of Line Chart absorb all gestures and so it stops the InteractiveViewer from panning the view.

I assume this is related to the refactoring of the touch system, and what should be used is another breaking change where the touchCallback returns a boolean where it says if it handled the gesture and such, to allow the gesture event to bubble up the chain.

**EDIT:** Checked the code and apparently it's best to simply stop setting handlers for all possible touch behaviors and instead pass handlers manually. https://github.com/imaNNeoFighT/fl_chart/blob/47d83844c10def4167f6bf16e8ab68693b8c82ae/lib/src/chart/base/base_chart/render_base_chart.dart#L50-L74  

**To Reproduce**
Soon ™️ 

**Screenshots**
This seems similar to the change in issue #772.

**Versions**
 - Flutter: stable 2.5.2
 - FlChart: 0.4.0

**Comment by praveengitsit** [comment]
Any updates on this? Been using **fl_chart** and now have a new requirement of having a zoom feature within the charts.

**Comment by imaNNeoFighT** [comment]
Zoom feature is discussed in another issue #71.
Interactive Viewer is not our preffered way to do this.
