### ISSUE TITLE
Show chart data from List<double> and List<DateTime> values

### ISSUE THREAD

**Issue by cc13com** [imaNNeo/fl_chart#803]
Hi,

I request data from a JSON interface and will show part of this data in a fl_chart.

First is a `List<DateTime>` called `timestamp`, second is `List<double>` called `close`. How can I put this values in a fl_chart to visualize? I need an idea how to implement.

I started with:

```
child: BarChart(
                                BarChartData(barGroups: [
                                      BarChartGroupData(x: 2, barRods: close)
                                ]),
                              )
```

But it gives me an `{"message": "The argument type 'List<double>' can't be assigned to the parameter type 'List<BarChartRodData>?'.",}`

**Comment by imaNNeo** [comment]
You need to map your data for example:
```dart
List<double> doubleValues = [1.0, 2.0, 8.0, 34.0];
List<FlSpot> spots = doubleValues.asMap().entries.map((e) {
  double x = e.key.toDouble();
  double y = e.value;
  return FlSpot(x, y);
}).toList();
```
