### ISSUE TITLE
Custom Border in BarChartData

### ISSUE THREAD

**Issue by mariusschroeter** [imaNNeo/fl_chart#806]
When working with BarChartData you can provide barRods and inside for example:

BarChartRodData(
        y: isLeft ? data + 1 : -data -1,
        width: 7.0,
        colors: Colors.black,
),

when i try to modify the y axis value it always starts at 0.

So for example if i want to create a margin to the border like here:

<img width="38" alt="Bildschirmfoto 2021-10-30 um 11 40 01" src="https://user-images.githubusercontent.com/43613156/139527967-69a2841c-8a49-45b5-a17f-1ccec62454fc.png">

I always get this result:

<img width="22" alt="Bildschirmfoto 2021-10-30 um 11 40 29" src="https://user-images.githubusercontent.com/43613156/139527979-08b7e141-61d7-4ea4-89f6-1e9668e29375.png">

even if i try to modify the y value.

**Comment by mariusschroeter** [comment]
i think i found the solution

**Comment by imaNNeoFighT** [comment]
Sorry, I didn't understand what you mean.
