### ISSUE TITLE
LineChart - Disable parent scrollview scroll gesture when displaying tooltip data 

### ISSUE THREAD

**Issue by dpacchi** [imaNNeo/fl_chart#810]
Hi, 
I was wondering if it could be possibile to disable the panning of a parent scrollview when panning on the line chart.
The use case is when you have this chart in an element of a list, and you don't want the list to scroll while you're exploring data by touching the line chart.

Thanks!

**Comment by imaNNeoFighT** [comment]
Hi, I don't know it is the user's responsibility or the chart's responsibility. But for now, you can disable ScrollView scroll by the below code. 
```dart
physics: NeverScrollableScrollPhysics(),
```
