### ISSUE TITLE
Rounded corners for Piechart

### ISSUE THREAD

**Issue by johanlantz** [imaNNeo/fl_chart#816]
Just started playing with this library. Great work, it is so much easier to use than the google one.

I have a small suggestion for your consideration. Having the possibility to round the corners in PieChart, it just looks much less "Powerpointy". Attaching an example from Lifecycle (and another one from Syncfusion where they have really gone all in, I am only interested in the option to slightly round the corners like in the first image).

![IMG_8490F2EA5A40-1](https://user-images.githubusercontent.com/7461655/142188987-def17516-1f0e-412f-9750-32618d8f5c1c.jpeg)

![IMG_8BFB3D1E0EA4-1](https://user-images.githubusercontent.com/7461655/142189006-deedae2c-5ea8-46a4-ab34-e8ca49df8075.jpeg)

**Comment by imaNNeo** [comment]
Please let's continue this issue in #1175.
Thanks
