### ISSUE TITLE
Radarchart out of memory error when all data goes zero

### ISSUE THREAD

**Issue by nkwook** [imaNNeo/fl_chart#826]
**Describe the bug**
I used example of radarchart which flchart team provided.
Once all of data values are zero like below screenshot,
![image](https://user-images.githubusercontent.com/47589404/142977801-4faccb5f-f571-4a91-bc7d-14d8bb0967dc.png)

App crashes and takes about 5 min to reproduce error message(Estimating somewhat infinite loop problem)

**Screenshots**
![image](https://user-images.githubusercontent.com/47589404/142977701-7886a189-dbdf-435c-afeb-5a2999d9b52e.png)

**Versions**
 - which version of the Flutter are you using? 2.5.1
 - which version of the FlChart are you using? 0.40.2

**Comment by eric-taix** [comment]
I had the same issue today. This happens not only when all `RadarEntry` are zero, but when all `RadarEntry` have the same value. As a workaround (until it has been fixed) you can add `0.00000001` to one of your entry.
