### ISSUE TITLE
Container -decoration-gradient  PieChart   can't show   web    --web-renderer html

### ISSUE THREAD

**Issue by chd999** [imaNNeo/fl_chart#827]
web    --web-renderer html

Container(
      width: 500,
      height: 500,
      decoration: BoxDecoration(
        color: Colors.cyan,
        gradient: LinearGradient(begin: Alignment.topCenter, end: Alignment.bottomCenter, colors:[Colors.black,Colors.white]),
      ),
      child: PieChart(PieChartData(
        centerSpaceRadius: 10,
        sections: pieData,
        borderData: FlBorderData(show: false),
       )
      ),
      );

**Comment by imaNNeo** [comment]
Please provide more information about the issue.
Also please test it again.

**Comment by imaNNeo** [comment]
It might be related to #955
