### ISSUE TITLE
Run chart on mobile doesn't work and makes app crash 

### ISSUE THREAD

**Issue by mickykro** [imaNNeo/fl_chart#856]
<img width="1222" alt="Screen Shot 2021-12-15 at 14 14 54" src="https://user-images.githubusercontent.com/60981756/146184875-93e2370f-c9cc-4aa7-bcd5-7dd72d11368e.png">

fl_chart: ^0.40.6

**Comment by imaNNeoFighT** [comment]
Can you please check it with the latest version of flutter and fl_chart?
