### ISSUE TITLE
Feature to clip the data point along with radius.

### ISSUE THREAD

**Issue by prajwal27** [imaNNeo/fl_chart#897]
**Describe the bug**
The Scatter chart in the image below does not clip the bubble.It considers only the data points. The `ScatterChartData` has a attribute called `clipData` , which checks if the data point is within the chart and then decides to clip it or not. 
However, it doesn't consider the radius of the bubble and hence, even if the data point is inside, the bubble might be so big that it causes it to go outside the axis, which is not a good UI/UX.

**To Reproduce**
It is fairly easy to reproduce. Take any example of scatter chart and increase the radius until you see it cross the axis.

**Screenshots**
![image](https://user-images.githubusercontent.com/95603936/153347535-e485e394-6eee-44cd-955e-ccc49631817b.png)

**Possible Solution**
So, currently we have clipped the bubble (see the topmost bubble), and it doesn't cross the chart, but it does cross the axis. So, what I feel would be a better idea is to crop clip the bubble inside the chart. So, we get something like this
![image](https://user-images.githubusercontent.com/95603936/153347359-37148589-2c5b-4216-b678-ebe236817f62.png)
Here, the bubble doesn't cross the axis.

**Versions**
 - Flutter version: 2.10.0
 - fl_chart version: 0.41.0

**Comment by imaNNeoFighT** [comment]
It has been fixed in [0.45.0](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.45.0) with your help :))
Thank you!
