### ISSUE TITLE
Feature/bug, grid titles overlap

### ISSUE THREAD

**Issue by eripe970** [imaNNeo/fl_chart#922]
Hey, 

I have a chart where I would like to control the overflow logic, is that possible? Tried different solutions but couldn't get anything to work. See screenshot below, would like to use TextOverflow.ellipsis when the label overflows. 

<img width="385" alt="Skärmavbild 2022-03-03 kl  14 28 44" src="https://user-images.githubusercontent.com/1668861/156574184-cee7964c-6572-40c3-b8d4-f3815e50268d.png">

**Comment by imaNNeoFighT** [comment]
Hi.
At the moment, there isn't any built-in solution.
But we are looking for a way to handle it locally.
As a workaround, you can rotate them a little bit.

**Comment by stukdev** [comment]
How? Rotate function in the latest versions is missing!

**Comment by imaNNeo** [comment]
> How? Rotate function in the latest versions is missing!

The change happened in the [0.55.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.50.0) version. You can take a look at the [0.50.0 migration guide](https://github.com/imaNNeo/fl_chart/blob/master/repo_files/documentations/migration_guides/0.50.0/MIGRATION_00_50_00.md).
