### ISSUE TITLE
Set threshold value and color to the line graph and bar graph

### ISSUE THREAD

**Issue by thamarakshan-pilla** [imaNNeo/fl_chart#984]
![WhatsApp Image 2022-04-25 at 1 09 34 PM](https://user-images.githubusercontent.com/69303422/165253661-5d98e6f4-c33a-46c7-8ecb-606a8580bfb7.jpeg)

The above example is what I want to achieve. 
This was done using normal linear gradient class. But instead I want to be able to set the threshold value and color for a line graph

**Comment by thamarakshan-pilla** [comment]
also would be nice if the same could be set for bar graph

**Comment by imaNNeo** [comment]
You need to modify [LinearGradient.stops](https://api.flutter.dev/flutter/painting/LinearGradient-class.html) to achieve your result.
